-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Mar 11, 2022 at 03:17 AM
-- Server version: 10.4.21-MariaDB
-- PHP Version: 8.0.11

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `candidates_db`
--

--
-- Dumping data for table `mayor_candidates`
--

INSERT INTO `mayor_candidates` (`id`, `candidate`, `sex`, `partylist`, `picture_dir`, `nickname`, `age`, `birthdate`, `hometown`, `honorary_degree`, `tertiary`, `political_background`, `regions`, `provinces`, `city_or_municipalities`) VALUES
(25, 'Onofre Abad', 'Male', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FIRST DISTRICT/CITY OF MANILA/Onofre Abad-NCR_NCR, FIRST DISTRICT_CITY OF MANILA_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Available Data ', 'No Available Data ', 'No Available Data ', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FIRST DISTRICT', 'CITY OF MANILA'),
(26, 'Amado Bagatsing ', 'Male', 'Kabalikat ng Bayan sa Kaunlaran (KABAKA)', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FIRST DISTRICT/CITY OF MANILA/Amado Bagatsing -NCR_NCR, FIRST DISTRICT_CITY OF MANILA_mayor.png', 'N/A', 74, '1947-12-03', 'N/A', 'No Available Data ', 'No Available Data ', 'No Available Data ', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FIRST DISTRICT', 'CITY OF MANILA'),
(27, 'Elmer Jamias', 'Male', 'People`s Reform Party ', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FIRST DISTRICT/CITY OF MANILA/Elmer Jamias-NCR_NCR, FIRST DISTRICT_CITY OF MANILA_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Available Data ', 'No Available Data ', 'No Available Data ', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FIRST DISTRICT', 'CITY OF MANILA'),
(28, 'Honey Lacuna ', 'Female', 'Asenso Manileño Movement / Aksyon Demokratiko', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FIRST DISTRICT/CITY OF MANILA/Honey Lacuna -NCR_NCR, FIRST DISTRICT_CITY OF MANILA_mayor.png', 'Honey', 56, '1965-05-06', 'N/A', 'No Data Available', 'BS Biology, University of Santo Tomas\r\n', 'Vice Mayor, Manila, 2016-Present | Director, Manila Social Welfare Department, 2013-2015 | Councilor, Manila 4th District, 2004-2013 ', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FIRST DISTRICT', 'CITY OF MANILA'),
(29, 'Christy Lim', 'Female', 'Partido Para sa Demokratikong Reporma', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FIRST DISTRICT/CITY OF MANILA/Christy Lim-NCR_NCR, FIRST DISTRICT_CITY OF MANILA_mayor.png', 'Christy ', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FIRST DISTRICT', 'CITY OF MANILA'),
(30, 'Alex Lopez', 'Male', 'Partido Federal ng Pilipinas', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FIRST DISTRICT/CITY OF MANILA/Alex Lopez-NCR_NCR, FIRST DISTRICT_CITY OF MANILA_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available\r\n', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FIRST DISTRICT', 'CITY OF MANILA'),
(31, 'Ben Abalos', 'Male', 'Partido Demokratiko Pilipino Lakas ng Bayan', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, SECOND DISTRICT/CITY OF MANDALUYONG/Ben Abalos-NCR_NCR, SECOND DISTRICT_CITY OF MANDALUYONG_mayor.png', 'Chairman Ben', 86, '1935-09-21', 'Pangasinan', 'No Available Data', 'AB Economics, Ateneo de Manila University | Bachelor of Laws, Manuel L. Quezon University', 'Officer-in-Charge Mayor of Mandaluyong, 1986–1987\r\nChairman of the Metropolitan Manila Development Authority,\r\n2001–2002 | COMELEC Chairman, 2002–2007', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, SECOND DISTRICT', 'CITY OF MANDALUYONG'),
(32, 'Florencio Solomon', 'Male', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, SECOND DISTRICT/CITY OF MANDALUYONG/Florencio Solomon-NCR_NCR, SECOND DISTRICT_CITY OF MANDALUYONG_mayor.png', 'Ricky', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, SECOND DISTRICT', 'CITY OF MANDALUYONG'),
(33, 'Bayani Fernando ', 'Male', 'Nationalist People`s Coalition ', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, SECOND DISTRICT/CITY OF MARIKINA/Bayani Fernando -NCR_NCR, SECOND DISTRICT_CITY OF MARIKINA_mayor.png', 'Bayani, BF', 75, '1946-07-25', 'San Juan del Monte, Rizal', 'Doctor of Humanities, Ateneo de Cagayan | Doctor of the Public Administration, Polytechnic \r\nUniversity of the Philippines', 'BS Mechanical Engineering, Mapua Institute of Technology | Manager`s Course (MC) for Small-Scale Industries, UP \r\nInstitute for Small-Scale Industries', 'Chairperson, Committee on Human Rights, 2019-present | President, Metro Manila Mayor`s League, 2000-2001', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, SECOND DISTRICT', 'CITY OF MARIKINA'),
(34, 'Marcy Teodoro', 'Male', 'United Nationalist Alliance', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, SECOND DISTRICT/CITY OF MARIKINA/Marcy Teodoro-NCR_NCR, SECOND DISTRICT_CITY OF MARIKINA_mayor.png', 'N/A', 51, '1970-08-02', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, SECOND DISTRICT', 'CITY OF MARIKINA'),
(35, 'Iyo Caruncho Bernardo', 'Male', 'People`s Reform Party', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, SECOND DISTRICT/CITY OF PASIG/Iyo Caruncho Bernardo-NCR_NCR, SECOND DISTRICT_CITY OF PASIG_mayor.png', 'Iyo, Christian', 50, '1971-06-25', 'Pasig City', 'No Data Available', 'BA Mass Communications: Trinity College | MA in Public Management (Currently Enrolled), Ateneo de Manila University', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, SECOND DISTRICT', 'CITY OF PASIG'),
(36, 'Vico Sotto ', 'Male', 'Aksyon Demokratiko', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, SECOND DISTRICT/CITY OF PASIG/Vico Sotto -NCR_NCR, SECOND DISTRICT_CITY OF PASIG_mayor.png', 'Vico', 32, '1989-06-17', 'Pasig City ', 'No Data Available', 'AB Political Science, Ateneo de Manila University | Masters in Public Administration, Ateneo School of Government', 'Executive Board Member, Government Watch, Inc.- present | Mayor, Pasig City- 2019-present – | Councilor, Pasig City - 2016-2019 | Legislative Staff officer V, Quezon City - 2013-2015', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, SECOND DISTRICT', 'CITY OF PASIG'),
(37, 'Glenda Araneta', 'Female', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, SECOND DISTRICT/QUEZON CITY/Glenda Araneta-NCR_NCR, SECOND DISTRICT_QUEZON CITY_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, SECOND DISTRICT', 'QUEZON CITY'),
(38, 'Ricardo Bello ', 'Male', 'Partido Demokratiko  Sosyalista ng Pilipinas', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, SECOND DISTRICT/QUEZON CITY/Ricardo Bello -NCR_NCR, SECOND DISTRICT_QUEZON CITY_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, SECOND DISTRICT', 'QUEZON CITY'),
(39, 'Joy Belmonte', 'Female', 'Serbisyo sa Bayan Party ', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, SECOND DISTRICT/QUEZON CITY/Joy Belmonte-NCR_NCR, SECOND DISTRICT_QUEZON CITY_mayor.png', 'N/A', 51, '1970-03-15', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, SECOND DISTRICT', 'QUEZON CITY'),
(40, 'Michael Defensor', 'Male', 'Partido Federal ng Pilipinas', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, SECOND DISTRICT/QUEZON CITY/Michael Defensor-NCR_NCR, SECOND DISTRICT_QUEZON CITY_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, SECOND DISTRICT', 'QUEZON CITY'),
(41, 'Jose Feliciano Ingles Jr. ', 'Male', 'Workers and Peasants Party AKA Labor Party Philippines', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, SECOND DISTRICT/QUEZON CITY/Jose Feliciano Ingles Jr. -NCR_NCR, SECOND DISTRICT_QUEZON CITY_mayor.png', 'Inventor Jose', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, SECOND DISTRICT', 'QUEZON CITY'),
(42, 'Rolando Jota', 'Male', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, SECOND DISTRICT/QUEZON CITY/Rolando Jota-NCR_NCR, SECOND DISTRICT_QUEZON CITY_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, SECOND DISTRICT', 'QUEZON CITY'),
(43, 'Emma Orozco', 'Female', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, SECOND DISTRICT/QUEZON CITY/Emma Orozco-NCR_NCR, SECOND DISTRICT_QUEZON CITY_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, SECOND DISTRICT', 'QUEZON CITY'),
(44, 'Tom Salutan', 'Male', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, SECOND DISTRICT/QUEZON CITY/Tom Salutan-NCR_NCR, SECOND DISTRICT_QUEZON CITY_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, SECOND DISTRICT', 'QUEZON CITY'),
(45, 'Diosdado Velasco', 'Male', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, SECOND DISTRICT/QUEZON CITY/Diosdado Velasco-NCR_NCR, SECOND DISTRICT_QUEZON CITY_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, SECOND DISTRICT', 'QUEZON CITY'),
(46, 'Jun Usman', 'Male', 'Pwersa ng Masang Pilipino', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, SECOND DISTRICT/CITY OF SAN JUAN/Jun Usman-NCR_NCR, SECOND DISTRICT_CITY OF SAN JUAN_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', '2013-2016 – Barangay Kagawad', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, SECOND DISTRICT', 'CITY OF SAN JUAN'),
(47, 'Francis Zamora', 'Male', 'Partido Demokratiko Pilipino Lakas ng Bayan', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, SECOND DISTRICT/CITY OF SAN JUAN/Francis Zamora-NCR_NCR, SECOND DISTRICT_CITY OF SAN JUAN_mayor.png', 'Francis', 42, '1977-12-05', 'San Juan City, Metro Manila', 'No Data Available', 'De La Salle University (DLSU)', '2019-Present – Mayor | 2016 – Ran for Mayor but lost to Guia Gomez by a small margin | 2010-2016 – Vice Mayor | 2007–2010 – Councilor', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, SECOND DISTRICT', 'CITY OF SAN JUAN'),
(48, 'Jun Anquilan', 'Male', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, THIRD DISTRICT/CALOOCAN CITY/Jun Anquilan-NCR_NCR, THIRD DISTRICT_CALOOCAN CITY_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, THIRD DISTRICT', 'CALOOCAN CITY'),
(49, 'Ruffy Bay-on', 'Male', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, THIRD DISTRICT/CALOOCAN CITY/Ruffy Bay-on-NCR_NCR, THIRD DISTRICT_CALOOCAN CITY_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, THIRD DISTRICT', 'CALOOCAN CITY'),
(50, 'Roman Domasig Jr.', 'Male', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, THIRD DISTRICT/CALOOCAN CITY/Roman Domasig Jr.-NCR_NCR, THIRD DISTRICT_CALOOCAN CITY_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, THIRD DISTRICT', 'CALOOCAN CITY'),
(51, 'Egay Erice', 'Male', 'Aksyon Demokratiko ', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, THIRD DISTRICT/CALOOCAN CITY/Egay Erice-NCR_NCR, THIRD DISTRICT_CALOOCAN CITY_mayor.png', 'Egay', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, THIRD DISTRICT', 'CALOOCAN CITY'),
(52, 'Dale Malapitan', 'Male', 'Partido Demokratiko Pilipino Laks ng Bayan', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, THIRD DISTRICT/CALOOCAN CITY/Dale Malapitan-NCR_NCR, THIRD DISTRICT_CALOOCAN CITY_mayor.png', 'Along', 42, '1979-10-31', 'Caloocon City, Metro Manila', 'Degree - Management', 'Colegio de San Juan de Letran', '2020-Present – Head, House of Representatives Electoral Tribunal | 2019-Present – Vice Chairperson, House Committee on Disaster\r\n Management | 2019-Present – Vice Chairperson, House Committee on Transportation | 2019-2020 – Chairperson, House Committee on Poverty Alleviation | 2016-Present – Congressman | 2013-2016 – Barangay Captain and President, Liga ng mga Barangay \r\nsa Caloocan City', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, THIRD DISTRICT', 'CALOOCAN CITY'),
(53, 'Toto Malunes', 'Male', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, THIRD DISTRICT/CALOOCAN CITY/Toto Malunes-NCR_NCR, THIRD DISTRICT_CALOOCAN CITY_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, THIRD DISTRICT', 'CALOOCAN CITY'),
(54, 'Enzo Oreta', 'Male', 'National Unity Party ', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, THIRD DISTRICT/CITY OF MALABON/Enzo Oreta-NCR_NCR, THIRD DISTRICT_CITY OF MALABON_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, THIRD DISTRICT', 'CITY OF MALABON'),
(55, 'Jeannie Sandoval', 'Female', 'Nacionalista Party', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, THIRD DISTRICT/CITY OF MALABON/Jeannie Sandoval-NCR_NCR, THIRD DISTRICT_CITY OF MALABON_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, THIRD DISTRICT', 'CITY OF MALABON'),
(56, 'Mario Camacho ', 'Male', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, THIRD DISTRICT/CITY OF NAVOTAS/Mario Camacho -NCR_NCR, THIRD DISTRICT_CITY OF NAVOTAS_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, THIRD DISTRICT', 'CITY OF NAVOTAS'),
(57, 'Raymond Alonzo Cruz', 'Male', 'Aksyon Demokratiko', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, THIRD DISTRICT/CITY OF NAVOTAS/Raymond Alonzo Cruz-NCR_NCR, THIRD DISTRICT_CITY OF NAVOTAS_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, THIRD DISTRICT', 'CITY OF NAVOTAS'),
(58, 'John Rey Tiangco', 'Male', 'Partido Naviteño', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, THIRD DISTRICT/CITY OF NAVOTAS/John Rey Tiangco-NCR_NCR, THIRD DISTRICT_CITY OF NAVOTAS_mayor.png', 'John Rey', 49, '1972-11-21', 'Navotas, Metro Manila', 'Bachelor of Science in Accounting | Bachelor of Arts in History', '2000, College of Saint Benilde | 1995, De La Salle University', 'Congressman:\r\n2019 – Present, Representative, Lone District of Navotas City\r\n\r\n| Mayor:   \r\n2016 – 2019, City of Navotas\r\n2013 – 2016, City of Navotas\r\n2010 – 2013, City of Navotas', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, THIRD DISTRICT', 'CITY OF NAVOTAS'),
(59, 'Bombit Bernardo ', 'Male', 'Lingkod ng Mamayan ng Valenzuela City', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, THIRD DISTRICT/CITY OF VALENZUELA/Bombit Bernardo -NCR_NCR, THIRD DISTRICT_CITY OF VALENZUELA_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, THIRD DISTRICT', 'CITY OF VALENZUELA'),
(60, 'Weslie Gatchalian', 'Male', 'Nationalist People`s Coalition', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, THIRD DISTRICT/CITY OF VALENZUELA/Weslie Gatchalian-NCR_NCR, THIRD DISTRICT_CITY OF VALENZUELA_mayor.png', 'Wes', 41, '1980-08-11', 'Valenzuela City, Metro Manila', 'Degree – Business and Operations Management', 'College – Bryant College, Rhode Island, USA | College – Oxford Brookes University, Oxford, \r\nUnited Kingdom | Master – London Metropolitan University, London, \r\nUnited Kingdom', '2020-Present – Deputy House Speaker | 2019-2020 – Chairperson, House Committee on Trade and Industry | 2016-Present – Congressman', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, THIRD DISTRICT', 'CITY OF VALENZUELA'),
(61, 'Antonio Abellar Jr.', 'Male', 'Partido Maharlika', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/CITY OF LAS PIÑAS/Antonio Abellar Jr.-NCR_NCR, FOURTH DISTRICT_CITY OF LAS PIÑAS_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'CITY OF LAS PIÑAS'),
(62, 'Imelda Aguilar', 'Female', 'Nacionalista Party', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/CITY OF LAS PIÑAS/Imelda Aguilar-NCR_NCR, FOURTH DISTRICT_CITY OF LAS PIÑAS_mayor.png', 'Mel', 75, '1946-10-31', 'Las Piñas CIty, Metro Manila', 'No Data Available', 'No Data Available', '2019-2022 – Mayor | 2016-2019 – Mayor | 2004-2007 – Mayor', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'CITY OF LAS PIÑAS'),
(63, 'Louie Casimiro ', 'Male', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/CITY OF LAS PIÑAS/Louie Casimiro -NCR_NCR, FOURTH DISTRICT_CITY OF LAS PIÑAS_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'CITY OF LAS PIÑAS'),
(64, 'Aladin De Jesus', 'Male', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/CITY OF LAS PIÑAS/Aladin De Jesus-NCR_NCR, FOURTH DISTRICT_CITY OF LAS PIÑAS_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'CITY OF LAS PIÑAS'),
(65, 'Ferdinand Camigla Eusebio', 'Male', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/CITY OF LAS PIÑAS/Ferdinand Camigla Eusebio-NCR_NCR, FOURTH DISTRICT_CITY OF LAS PIÑAS_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'CITY OF LAS PIÑAS'),
(66, 'Benjamin Gonzales', 'Male', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/CITY OF LAS PIÑAS/Benjamin Gonzales-NCR_NCR, FOURTH DISTRICT_CITY OF LAS PIÑAS_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'CITY OF LAS PIÑAS'),
(67, 'Simnar Gran', 'Male', 'Partido Para sa Demokratikong Reporma', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/CITY OF LAS PIÑAS/Simnar Gran-NCR_NCR, FOURTH DISTRICT_CITY OF LAS PIÑAS_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'CITY OF LAS PIÑAS'),
(68, 'Michael Maestrado', 'Male', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/CITY OF LAS PIÑAS/Michael Maestrado-NCR_NCR, FOURTH DISTRICT_CITY OF LAS PIÑAS_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'CITY OF LAS PIÑAS'),
(69, 'Rey Rivera', 'Male', 'Alliance for the Common Good - Kapatiran Party', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/CITY OF LAS PIÑAS/Rey Rivera-NCR_NCR, FOURTH DISTRICT_CITY OF LAS PIÑAS_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'CITY OF LAS PIÑAS'),
(70, 'Mar-Len Abigail Binay', 'Female', 'Makatizens United Party', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/CITY OF MAKATI/Mar-Len Abigail Binay-NCR_NCR, FOURTH DISTRICT_CITY OF MAKATI_mayor.png', 'Abby', 46, '1975-12-12', 'N/A', 'No Data Available', 'Ateneo School of Law, 1997 - 2001 | UP Los Baños, Laguna', 'City Mayor, 2016 to present | City Government of Makati\r\nCongresswoman, 2007-2016 | House of Representatives | Lawyer, 2002-2007', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'CITY OF MAKATI'),
(71, 'Joel Hernandez', 'Male', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/CITY OF MAKATI/Joel Hernandez-NCR_NCR, FOURTH DISTRICT_CITY OF MAKATI_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'CITY OF MAKATI'),
(72, 'Nelson Benjamin', 'Male', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/CITY OF MUNTINLUPA/Nelson Benjamin-NCR_NCR, FOURTH DISTRICT_CITY OF MUNTINLUPA_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'CITY OF MUNTINLUPA'),
(73, 'Rozzano Rufino Biazon', 'Male', 'One Muntinlupa', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/CITY OF MUNTINLUPA/Rozzano Rufino Biazon-NCR_NCR, FOURTH DISTRICT_CITY OF MUNTINLUPA_mayor.png', 'Ruffy Biazon', 52, '1969-03-20', 'Muntinlupa City, Metro Manila', 'Degree - Medical Technology', 'University of Santo Tomas', '2019-Present – Vice Chairperson, House Committee on Appropriations | 2019-Present – Vice Chairperson, House Committee on National Defense and Security |2001-2010, 2016-Present – Congressman | 2011-2013 – Commissioner, Bureau of Customs | 1991-1992 – Director, Videogram Regulatory Board', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'CITY OF MUNTINLUPA'),
(74, 'Marc Red Mariñas ', 'Male', 'People`s Reform Party', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/CITY OF MUNTINLUPA/Marc Red Mariñas -NCR_NCR, FOURTH DISTRICT_CITY OF MUNTINLUPA_mayor.png', 'Red', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'CITY OF MUNTINLUPA'),
(75, 'Oscar Marmeto', 'Male', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/CITY OF MUNTINLUPA/Oscar Marmeto-NCR_NCR, FOURTH DISTRICT_CITY OF MUNTINLUPA_mayor.png', 'Oscar', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'CITY OF MUNTINLUPA'),
(76, 'Rolando Aguilar', 'Male', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/CITY OF PARAÑAQUE/Rolando Aguilar-NCR_NCR, FOURTH DISTRICT_CITY OF PARAÑAQUE_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'CITY OF PARAÑAQUE'),
(77, 'Gerardo Mores', 'Male', 'Pederalismo ng Dugong Dakilang Samahan', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/CITY OF PARAÑAQUE/Gerardo Mores-NCR_NCR, FOURTH DISTRICT_CITY OF PARAÑAQUE_mayor.png', 'Jherie', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'CITY OF PARAÑAQUE'),
(78, 'Eric Olivarez', 'Male', 'Partido Demokratiko Pilipino Lakas ng Bayan', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/CITY OF PARAÑAQUE/Eric Olivarez-NCR_NCR, FOURTH DISTRICT_CITY OF PARAÑAQUE_mayor.png', 'Eric', 0, '0000-00-00', 'N/A', 'History and Political Science', 'De La Salle University', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'CITY OF PARAÑAQUE'),
(79, 'John Drew Uy', 'Male', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/CITY OF PARAÑAQUE/John Drew Uy-NCR_NCR, FOURTH DISTRICT_CITY OF PARAÑAQUE_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'CITY OF PARAÑAQUE'),
(80, 'Julius Anthony Zaide', 'Male', 'Kilusang Bagong Lipunan', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/CITY OF PARAÑAQUE/Julius Anthony Zaide-NCR_NCR, FOURTH DISTRICT_CITY OF PARAÑAQUE_mayor.png', 'Jun', 39, '1982-08-28', 'N/A', 'Foreign Service (Major in Diplomacy)', 'Lyceum of the Philippines University', 'Baranggay Captain', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'CITY OF PARAÑAQUE'),
(81, 'Richard Advincula ', 'Male', 'People`s Reform Party ', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/PASAY CITY/Richard Advincula -NCR_NCR, FOURTH DISTRICT_PASAY CITY_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'Former City Counciler', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'PASAY CITY'),
(82, 'Imelda Calixto-Rubiano', 'Female', 'Partido Demokratiko Pilipino Lakas ng Bayan ', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/PASAY CITY/Imelda Calixto-Rubiano-NCR_NCR, FOURTH DISTRICT_PASAY CITY_mayor.png', 'Emi', 61, '1960-08-16', 'Pasay City, Metro Manila', 'No Data Available', 'Bachelor of Arts Major in Behavioral Science - University of Santo Tomas', '2019-Present – Mayor | 2010-2019 – Congresswoman, Pasay City | 1998-2004, 2007-2010 – Councilor', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'PASAY CITY'),
(83, 'AJ Romero ', 'Male', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/PASAY CITY/AJ Romero -NCR_NCR, FOURTH DISTRICT_PASAY CITY_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'PASAY CITY'),
(84, 'Edward Togonon ', 'Male', 'Partido sa Demokratikong Reporma', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/PASAY CITY/Edward Togonon -NCR_NCR, FOURTH DISTRICT_PASAY CITY_mayor.png', 'ET', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'PASAY CITY'),
(85, 'Marilyn Chiong', 'Female', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/PATEROS/Marilyn Chiong-NCR_NCR, FOURTH DISTRICT_PATEROS_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'PATEROS'),
(86, 'Miguel E Ponce III', 'Male', 'Aksyon Demokratiko', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/PATEROS/Miguel E Ponce III-NCR_NCR, FOURTH DISTRICT_PATEROS_mayor.png', 'Ike ', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'PATEROS'),
(87, 'Maria Laarni Cayetano', 'Female', 'Nacionalista Party', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/TAGUIG CITY/Maria Laarni Cayetano-NCR_NCR, FOURTH DISTRICT_TAGUIG CITY_mayor.png', 'Lani', 40, '1981-12-11', 'N/A', 'No Data Available', 'No Data Available', '2007-2010, 2019-Present –Congresswoman | 2010-2019 – Mayor', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'TAGUIG CITY'),
(88, 'Arnel Cerafica ', 'Male', 'Partido Pilipino sa Pagbabago (PPP) ', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/TAGUIG CITY/Arnel Cerafica -NCR_NCR, FOURTH DISTRICT_TAGUIG CITY_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'TAGUIG CITY');

--
-- Dumping data for table `pres_candidates`
--

INSERT INTO `pres_candidates` (`id`, `candidate`, `sex`, `partylist`, `picture_dir`, `nickname`, `age`, `birthdate`, `hometown`, `honorary_degree`, `tertiary`, `political_background`, `stance_divorce`, `stance_death_penalty`, `stance_same_sex_marriage`) VALUES
(71, 'Ernie Abella', 'Male', 'Independent', '../pictures/presidents/Ernie Abella-president.png', 'Ernie', 72, '1972-07-11', 'Davao City, Davao Region', 'No Data Available', 'Ateneo de Davao University - \r\nBA in pre-medicine | Silliman University - Master`s Degree in Divinity | Asian Institute of Management - Master`s Degree in Social Development', 'Undersecretary for Strategic \r\nCommunications and Research of the Department of Foreign Affairs (2017–2021).| Presidential Spokesperson (2016–2017)', 'Unknown', 'Yes', 'Unknown'),
(72, 'Leody De Guzman', 'Male', 'Partido Lakas ng Masa', '../pictures/presidents/Leody De Guzman-president.png', 'Ka Leody', 62, '1959-07-25', 'Naujan, Oriental Mindoro', 'No Data Available', 'Philippine Maritime Institute - Bachelor of Science in Customs Administration', 'Chairman - Bukluran ng Manggagawang Pilipino (BMP) | Councilor - International Council, International Center for Labor Solidarity | Vice President - Asia Regional Organization of Bank, Insurance and Finance Unions', 'Yes', 'No', 'Yes'),
(73, 'Isko Moreno Domagoso ', 'Male', 'Aksyon Demokratiko', '../pictures/presidents/Isko Moreno Domagoso -president.png', 'Yorme', 47, '1974-10-24', 'Manila, Philippines', 'No Data Available', 'Harvard University - Executive Leadership Program | Oxford University - Strategic Leadership Program | US State Department in Washington DC - International Visitor Leadership Program | University of the Philippines, Diliman - Executive Leadership Program | Pamantasan ng Lungsod ng Maynila - Public Administration | Arellano University - Bachelor of Laws', 'Councilor of Manila, 1st District (1998-2007) | Manila Vice Mayor (2007-2013, 2013-2016) | Chairman of the Board of the North Luzon Railways Corporation (July 2017--October 2017) | Undersecretary of Social Welfare and Development for Luzon Affairs (May2018 - October 2018) | 27th Mayor of Manila (2019-present)', 'No', 'No', 'No'),
(74, 'Norberto Gonzales', 'Male', 'Partido Demokratiko Sosyalista ng Pilipinas', '../pictures/presidents/Norberto Gonzales-president.png', 'N/A', 74, '1947-04-17', 'Balanga, Bataan', 'No Data Available', 'Ateneo de Davao University - Bachelor of Science in Pre-Medicine | National Defense College of the Philippines - Master in National Security Administration', '36th Secretary of the Department of the National Defense of the Philippines under the administration of President Gloria Macapagal Arroyo | Presidential Adviser for Special Concerns to President Gloria Macapagal-Arroyo (February 2001 to January 2004) | Arroyo`s Presidential Chief of Staff (August 2004 - February 2005) | National Security Adviser and Director-General of the National Security Council.(February of 2005 - June of 2010)', 'Unknown', 'Unknown', 'Unknown'),
(75, 'Faisal Mangondato', 'Male', 'Katipunan ng Kamalayang Kayumanggi ', '../pictures/presidents/Faisal Mangondato-president.png', 'Fai', 59, '1962-12-30', 'Ramain Ditsaan, Lanao del Sur', 'No Data Available', 'B.S. Medical Technology, Philippine Women`s University', 'No Data Available', 'Yes', 'Yes', 'Yes'),
(76, 'Ping Lacson', 'Male', 'Partido Para sa Demokratikong Reporma', '../pictures/presidents/Ping Lacson-president.png', 'Ping', 73, '1948-06-01', 'Imus, Cavite', 'No Data Available', 'Masters in Government Management\r\nPamantasan ng Lungsod ng Maynila (1995-1996)', 'Senator (2001-2013, 2016-present) Presidential Assistant for Rehabilitation and Recovery', 'Yes', 'Unknown', 'No'),
(77, 'Bongbong Marcos', 'Male', 'Partido Federal ng Pilipinas', '../pictures/presidents/Bongbong Marcos-president.png', 'Bongbong', 65, '1957-09-13', 'Ilocos Norte', 'No Data Available', 'Special Diploma in Social Studies, Oxford University', 'Senator of the Philippines (2010-2016) | Congressman, Ilocos Norte (2nd District) (2007-2010) | Governor, Ilocos Norte (1998-2007) | Congressman, Ilocos Norte (2nd District) (1992-1995) | Governor, Ilocos Norte (1983-1986) | Vice-Governor, Ilocos Norte (1980-1983)', 'Unknown', 'Yes', 'Yes'),
(78, 'Jose Montemayor Jr.', 'Male', 'Democratic Party of the Philippines', '../pictures/presidents/Jose Montemayor Jr.-president.png', 'Jojomo', 73, '1948-06-01', 'Imus, Cavite', 'No Data Available', 'Master of Divinity, Farcorner`s International Theological Seminary | Phd Public Health, Ruggero Univ. | International Master of Laws (LL.M. Cand.) - Human Rights, Ateneo de Manila University | Masters in Business Administration, University of the Philippines | Bachelor of Laws (LLB), Philippine Law School | Research fellow in cardiac catheterization, St. Luke`s Heart Institute | Fellowship in adult cardiology, St. Luke’s Heart Institute | Post graduate internship and residency in internal medicine, Cardinal Santos Medical Center | Doctor of Medicine, Far Eastern University | B.S. Medical Technology, Far Eastern University', 'No Data Available', 'No', 'Unknown', 'Unknown'),
(79, 'Manny Pacman Pacquiao', 'Male', 'Abag Promdi', '../pictures/presidents/Manny Pacman Pacquiao-president.png', 'Manny', 43, '1978-12-17', 'General Santos City', 'Doctorate of Humanities, \r\nSouthwestern University', 'Bachelor`s Degree in Political Science Majoring in Local Government Administration through the Expanded Tertiary Education Equivalency and Accreditation Program (ETEEAP), Philippine Councilors League-Legislative Academy ,2019 | BSBA Marketing Management, Notre Dame of Dadiangas University | Political Science, University of Makati\r\n', 'Representative Sarangani Province, 15th Congress, 2010 to 2013 | Representative Sarangani Province, 16th Congress, 2013 to 2016 | Senator, 17th Congress, 2016', 'Yes', 'Yes', 'No'),
(80, 'Leni Robredo', 'Female', 'Independent', '../pictures/presidents/Leni Robredo-president.png', 'Leni', 57, '1965-04-23', 'Naga, Camarines Sur', 'Doctor in Public Administration, Polytechnic University of the Philippines | Doctor of Humanities, University of Saint Anthony in Naga City | Doctor of Laws, University of the Cordilleras in Baguio City', 'B.A. in Economics, University of the Philippines-Diliman | Juris Doctor, University of Nueva Caceres | Passed the Bar Examinations in 1996 and admitted to the Philippine Bar Association', 'Vice President of the Philippines, 2016 | Representative of the 3rd District of Camarines Sur, 2013 to 2016', 'No', 'No', 'No');

--
-- Dumping data for table `vcpres_candidates`
--

INSERT INTO `vcpres_candidates` (`id`, `candidate`, `sex`, `partylist`, `picture_dir`, `nickname`, `age`, `birthdate`, `hometown`, `honorary_degree`, `tertiary`, `political_background`, `stance_divorce`, `stance_death_penalty`, `stance_same_sex_marriage`) VALUES
(11, 'Lito Atienza', 'Male', 'Abag Promdi', '../pictures/vc_presidents/Lito Atienza-vcpresident.png', 'Lito', 80, '1941-08-10', 'San Andres Bukid, Manila', 'Doctor of Public Management, Honoris Causa, Pamantasan ng Lungsod ng Maynila', 'Master in Urban Planning, Pamantasan ng Lungsod ng Maynila | Bachelor in Public Administration, Pamantasan ng Lungsod ng Maynila\r\n', 'Deputy Speaker of the House of Representatives, Nov. 2020 to present | Representative of Buhay Party-List Group, House of Representatives, 2013 to present | Secretary, Department of Environment and Natural Resources, 2007 to 2009 | Mayor, Manila City, 1998 - 2007 | Vice Mayor, Manila City, 1992 - 1998', 'Unknown', 'Unknown', 'Unknown'),
(12, 'Walden Bello ', 'Male', 'Partido Lakas ng Masa ', '../pictures/vc_presidents/Walden Bello -vcpresident.png', 'N/A', 76, '1945-11-11', 'Cardona , Rizal', 'No Data Available', 'BA in Humanities, Ateneo de Manila University, 1966 | MA in Sociology, Princeton University, 1972 | Ph.D in Sociology, Princeton University, 1975', 'Akbayan Representative, 14th Congress, served from 2009 to 2010 | Akbayan Representative, 15th Congress, 2010 to 2013 | Akbayan Representative, 14th Congress, 2013 to 2015 (resigned)', 'Unknown', 'Unknown', 'Unknown'),
(13, 'Rizalito David', 'Male', 'Democratic Party of the Philippines', '../pictures/vc_presidents/Rizalito David-vcpresident.png', 'N/A', 60, '1962-01-12', 'Tondo, Manila', 'No Data Available', 'Sociology and Environmental Science (minor in Rural Development), University of the Philippines - Los Baños', 'Council Member, Koalisyong Katoliko Kristyano | Executive Director, Pro-Life Philippoines, Inc.| Radio commentator, Radio Veritas, Gising Kapatid and Turo ni Ina | Head Executive Assistant and Political Affairs Director, Sen. Robert Jaworski, Philippine Senate, 1998 - 2004 | Consultant on Political Affairs and Head of Political Operations in Mindanao, Deputy Speaker Hernando Perez, Houses of Representatives, 1997 - 1998 | Executive Assistant (1993 - 1995) and Political Affairs Director (1995 - 1996), Sen. Francisco Tatad, Philippine Senate | Chief, Research Monitoring Staff, Liberal Party-PDP Laban 1992 Presidential Elections, 1992 | Former Chief, Strategic Planning Section, Department of Environment and Natural Resources, 1990 - 1992\r\n', 'Unknown', 'Unknown', 'Unknown'),
(14, 'Sara Duterte', 'Female', 'Lakas Christian Muslim Democrats', '../pictures/vc_presidents/Sara Duterte-vcpresident.png', 'Inday Sara', 43, '1978-05-31', 'Davao City', 'No Data Available', 'Admitted to the Philippine Bar, 2005 | Bachelor of Laws, San Sebastian College – Recoletos, 2005 | Bachelor of Science, Respiratory Therapy, San Pedro College, 1999', 'Mayor, Davao City, 2010 - 2013; 2016 - present | Partner, Carpio & Duterte Lawyers, 2013 - 2016 | Chairman, Board-Regional Development Committee-Mindanao Area Committee of the National Economic and Development Authority | Chairperson, Regional Development Council | Vice Mayor, Davao City, 2007 – 2010 | Court Attorney, Office of the Associate Justice Romeo J. Carpio Sr., Supreme Court', 'Unknown', 'Unknown', 'Unknown'),
(15, 'Manny Lopez SD', 'Male', 'Workers and Peasants Party', '../pictures/vc_presidents/Manny Lopez SD-vcpresident.png', 'N/A', 63, '2022-03-10', 'Moncada, Tarlac', 'No Data Available', 'Business Economics Program, University of Asia and the Pacific Juris Doctor, Pacific Coast University | Business Law, Los Angeles City College | MBA, University of California, Los Angeles | Political Science and Economics, University of the Philippines - Diliman, 1981', 'Vice Chairman, National Advisory Board, Labor Party of the Philippines (a.k.a. The Workers and Peasants Party | President and General Manager at NFA Grainscor\r\n', 'Unknown', 'Unknown', 'Unknown'),
(16, 'Doc Willie Ong', 'Male', 'Aksyon Demokratiko', '../pictures/vc_presidents/Doc Willie Ong-vcpresident.png', 'N/A', 58, '1963-10-24', 'Tondo, Manila City', 'No Data Available', 'B.S. Botany, University of the Philippines-Diliman | Medical degree, De La Salle Health Science Institute | Masters in Public Health, UP - Manila', 'No Data Available', 'Unknown', 'Unknown', 'Unknown'),
(17, 'Francis Nepomuceno Pangilinan', 'Male', 'Liberal Party', '../pictures/vc_presidents/Francis Nepomuceno Pangilinan-vcpresident.png', 'Kiko', 58, '1963-08-24', 'Manila City, Metro Manila', 'No Data Available', 'Bachelor of Arts in English, Major in Comparative Literature, University of the Philippines Diliman | Bachelor of Laws, University of the Philippines Diliman | Masters in Public Administration, John F. Kennedy School of Government Harvard University Cambridge, 1997', 'Member, Senate Electoral Tribunal 18th Congress, July 2020 – present | Campaign Manager, Otso Diretso Senate slate (Liberal Party coalition), Feb. - May 2019 | Minority Leader, Commission on Appointments 17th to 18th Congress, May 2017 – June 2020 | Senator 17th to 18th Congress, June 2016 – present | Cabinet Secretary, Presidential Assistant for Food Security and Agricultural | Modernization - Office of the President, May 2014 – Sept. 2015 | Campaign Manager, Liberal Party Senate slate, Feb. - May 2010 | Senate Majority Leader, 2004 – 2008 | Senator, 12th to 14th Congress, 2001 – 2013', 'Unknown', 'Unknown', 'Unknown'),
(18, 'Carlos Gelacio Serapio ', 'Male', 'Katipunan ng Kamalayang Kayumanggi ', '../pictures/vc_presidents/Carlos Gelacio Serapio -vcpresident.png', 'N/A', 71, '1950-10-04', 'N/A', 'No Data Available', 'Serapio & de Castro Law Offices | Office of the Executive Secretary of President Benigno Aquino - Lead of Consultant Pool | Office of the Presidential Adviser on Political Affairs - Consultant | National Coastwatch Center - Office of the President - Consultant | United Nations Development Programme Local Democracy Project in Asia - Consultant | USAID Inventory and Database Project for the Court of Tax Appeals - Project Manager | Author, Christianism: A Philosophical Guide to Political Praxis | Chair and operator, LABAN Poll Watching Operations Center (1978)', 'LLB,University of the Philippines, 1975 | AB Political Science, Ateneo de Manila University, 1970', 'Unknown', 'Unknown', 'Unknown'),
(19, 'Vicente Castelo Sotto III', 'Male', 'Nationalist People`s Coalition ', '../pictures/vc_presidents/Vicente Castelo Sotto III-vcpresident.png', 'Tito Sotto', 73, '1948-08-24', 'N/A', 'No Data Available', 'Executive Program for Leaders in Development at the Harvard \r\nUniversity John F. Kennedy School of Government that he \r\ncompleted in June 2000 | AB English, Colegio de San Juan de Letran', 'Senate President (2018-present) | Senate Majority Floor Leader (2016-2018) | Senator (2013-2016) | Senate Majority Floor Leader (2010-2013) | Dangerous Drugs Board chairman (2008-2009) | Senator (1998-2004) | Senator (1992-1998)\r\n', 'Unknown', 'Unknown', 'Unknown');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
