-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Mar 12, 2022 at 05:35 AM
-- Server version: 10.4.22-MariaDB
-- PHP Version: 8.0.13

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `candidates_db`
--

-- --------------------------------------------------------

--
-- Table structure for table `governor_candidates`
--

CREATE TABLE `governor_candidates` (
  `id` int(255) NOT NULL,
  `candidate` varchar(255) NOT NULL,
  `sex` varchar(255) NOT NULL,
  `partylist` varchar(255) NOT NULL,
  `picture_dir` text NOT NULL,
  `nickname` varchar(255) NOT NULL,
  `age` int(255) NOT NULL,
  `birthdate` date NOT NULL,
  `hometown` varchar(255) NOT NULL,
  `honorary_degree` text NOT NULL,
  `tertiary` text NOT NULL,
  `political_background` text NOT NULL,
  `regions` varchar(255) NOT NULL,
  `provinces` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `governor_candidates`
--

INSERT INTO `governor_candidates` (`id`, `candidate`, `sex`, `partylist`, `picture_dir`, `nickname`, `age`, `birthdate`, `hometown`, `honorary_degree`, `tertiary`, `political_background`, `regions`, `provinces`) VALUES
(33, 'Takit Bersamin', 'Male', 'Partido Para sa Demokratikong Reporma', '../pictures/governors/CORDILLERA ADMINISTRATIVE REGION (CAR)/ABRA/Takit Bersamin-CAR_ABRA_governor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', '2007-2010 -Provincial Governor of Abra Province | 2010-2013 - Provincial Governor of Abra Province', 'CORDILLERA ADMINISTRATIVE REGION (CAR)', 'ABRA'),
(34, 'Nic Valera', 'Male', 'National Unity Party', '../pictures/governors/CORDILLERA ADMINISTRATIVE REGION (CAR)/ABRA/Nic Valera-CAR_ABRA_governor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', '2019-2022 - Municipal Mayor', 'CORDILLERA ADMINISTRATIVE REGION (CAR)', 'ABRA'),
(35, 'Butzy Bulut', 'Male', 'National People`s Coalition', '../pictures/governors/CORDILLERA ADMINISTRATIVE REGION (CAR)/APAYAO/Butzy Bulut-CAR_APAYAO_governor.jpg', 'N/A', 51, '1970-05-15', 'N/A', 'No Data Available', 'No Data Available', '2001-2007 - House of Representatives of the Philippines, Lone District of Apayao ', 'CORDILLERA ADMINISTRATIVE REGION (CAR)', 'APAYAO'),
(36, 'Robert Namoro', 'Male', 'Partido Federal ng Pilipinas', '../pictures/governors/CORDILLERA ADMINISTRATIVE REGION (CAR)/BENGUET/Robert Namoro-CAR_BENGUET_governor.png', 'N/A', 54, '1967-09-17', 'N/A', 'No Data Available', 'Mountain State Agricultural College', '2002 - Punong Barangay', 'CORDILLERA ADMINISTRATIVE REGION (CAR)', 'BENGUET'),
(37, 'Melchor Diclas', 'Male', 'PDP - Laban', '../pictures/governors/CORDILLERA ADMINISTRATIVE REGION (CAR)/BENGUET/Melchor Diclas-CAR_BENGUET_governor.png', 'N/A', 0, '0000-00-00', 'Buguias, Benguet', 'No Data Available\r\n', 'No Data Available\r\n', '2016-2019 - Mayor', 'CORDILLERA ADMINISTRATIVE REGION (CAR)', 'BENGUET'),
(39, 'Jerry Dalipog', 'Male', 'Kilusang Bagong Lipunan', '../pictures/governors/CORDILLERA ADMINISTRATIVE REGION (CAR)/IFUGAO/Jerry Dalipog-CAR_IFUGAO_governor.png', 'N/A', 58, '1964-02-20', 'N/A', 'No Data Available\r\n\r\n', 'No Data Available\r\n\r\n', '2019-2022 - Governor | 2016-2019 - Municipal Mayor', 'CORDILLERA ADMINISTRATIVE REGION (CAR)', 'IFUGAO'),
(40, 'Conrado Dieza Jr.', 'Male', 'Partido Federal ng Pilipinas', '../pictures/governors/CORDILLERA ADMINISTRATIVE REGION (CAR)/KALINGA/Conrado Dieza Jr.-CAR_KALINGA_governor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available\r\n\r\n', 'No Data Available\r\n\r\n', 'No Data Available\r\n\r\n', 'CORDILLERA ADMINISTRATIVE REGION (CAR)', 'KALINGA'),
(41, 'James Edduba', 'Male', 'Lakas Christian Muslim Democrats', '../pictures/governors/CORDILLERA ADMINISTRATIVE REGION (CAR)/KALINGA/James Edduba-CAR_KALINGA_governor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available\r\n\r\n', 'No Data Available\r\n\r\n', '2010-2013, 2013-2016 - Mayor of Pasil, Kalinga | 2016-2019 - Vice Governor', 'CORDILLERA ADMINISTRATIVE REGION (CAR)', 'KALINGA'),
(42, 'Bonifacio Lacwasan Jr. ', 'Male', 'Partido Demokratika Pilipino Lakas ng Bayan', '../pictures/governors/CORDILLERA ADMINISTRATIVE REGION (CAR)/MOUNTAIN PROVINCE/Bonifacio Lacwasan Jr. -CAR_MOUNTAIN PROVINCE_governor.png', 'Boni', 63, '1958-09-15', 'Bauko, Mountain Province ', 'No Data Available\r\n\r\n', '1982  University of Manila', '2016-Presennt - Governor\r\n| 2010-2016 - Vice Governor | 1994-2007 - Barangay Captain of Otucan Sur, Bauko ', 'CORDILLERA ADMINISTRATIVE REGION (CAR)', 'MOUNTAIN PROVINCE'),
(43, 'Rudy Fariñas', 'Male', 'Partido Para sa Demokratikong Reporma', '../pictures/governors/REGION I (ILOCOS REGION)/ILOCOS NORTE/Rudy Fariñas-01_ILOCOS NORTE_governor.png', 'N/A', 70, '1951-09-05', 'N/A', 'No Data Available\r\n\r\n', 'Ateneo de Manila Law School ', '1980 - 1986 - Mayor, Laoag City |\r\n1988 - 1998 - Governor, Ilocos Norte | 1998 - 2001 - House Of Rep. Ilocos, Norte 1st District | 2010 - 2019 - House Of Rep. Ilocos, Norte 1st District', 'REGION I (ILOCOS REGION)', 'ILOCOS NORTE'),
(44, 'Matthew Monotoc', 'Male', 'Nacionalista Party', '../pictures/governors/REGION I (ILOCOS REGION)/ILOCOS NORTE/Matthew Monotoc-01_ILOCOS NORTE_governor.png', 'N/A', 33, '1988-12-09', 'Batac, Ilocos Norte', 'No Data Available\r\n\r\n', 'International School Manila | Ateneo de Manila University | Claremont McKenna College | University of California, Los Angeles', '2016 - 2019 - Member of the Ilocos Norte Provincial Board from the 2nd district | 2019 - 2022 - Governor, Ilocos Norte', 'REGION I (ILOCOS REGION)', 'ILOCOS NORTE'),
(45, 'Jerry Singson', 'Male', 'Nationalist People`s Coalition', '../pictures/governors/REGION I (ILOCOS REGION)/ILOCOS SUR/Jerry Singson-01_ILOCOS SUR_governor.png', 'N/A', 73, '1948-09-15', 'Ilocos Sur', 'No Data Available\r\n\r\n', 'University of Santo Tomas', '1988 - 1995 - Mayor, Vigan | 1995 - 2001, 2004 - 2007 -  Ilocos Sur Provincial Board Member, 1st District | 2001 - 2004, 2007 - 2010, 2016 - | 2022 - Vice Governor, Ilocos Sur', 'REGION I (ILOCOS REGION)', 'ILOCOS SUR'),
(46, 'Rafy David-Ortega', 'Female', 'Pederalismo ng Dugong Dakilang Samahan', '../pictures/governors/REGION I (ILOCOS REGION)/LA UNION/Rafy David-Ortega-01_LA UNION_governor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available\r\n\r\n', 'No Data Available\r\n\r\n', 'No Data Available\r\n\r\n', 'REGION I (ILOCOS REGION)', 'LA UNION'),
(47, 'Amado Espino III', 'Male', 'Abante Pangasinan Ilokano ', '../pictures/governors/REGION I (ILOCOS REGION)/PANGASINAN/Amado Espino III-01_PANGASINAN_governor.png', 'Pogi Espino ', 44, '1977-11-26', 'N/A', 'No Data Available\r\n\r\n', 'No Data Available\r\n\r\n', '2016-2022 - Governor of Pangasinan', 'REGION I (ILOCOS REGION)', 'PANGASINAN'),
(48, 'Ramon Guico III', 'Male', 'Nacionalista Party', '../pictures/governors/REGION I (ILOCOS REGION)/PANGASINAN/Ramon Guico III-01_PANGASINAN_governor.png', 'Mon-mon', 45, '1975-03-19', 'N/A', 'Degree - Philosophy | Master – Master of Arts in Educational Management | Doctorate – Ph.D. in Public Management', 'University of the Philippines Diliman\r\n| Pamantasan ng Lungsod Ng Maynila', '2019-Present – Chairperson, House \r\nCommittee on North Luzon Growth Quadrangle | 2019-Present – Vice Chairperson, House Committee on Transportation | 2019-Present – Congressman of fifth district \r\ncovering the City of Urdaneta and the municipalities of Alcala, Bautista, Binalonan, Laoac, Pozorrubio, Santo Tomas, Sison, and Villasis | 2010-2019 – Mayor, Binalonan | 2007-2010 – Vice Mayor of Binalonan', 'REGION I (ILOCOS REGION)', 'PANGASINAN'),
(49, 'Telesforo Castillejos', 'Male', 'Naciolist People`s Coalition', '../pictures/governors/REGION II (CAGAYAN VALLEY)/BATANES/Telesforo Castillejos-02_BATANES_governor.png', 'N/A', 75, '1947-01-05', 'N/A', 'No Data Available\r\n\r\n', 'No Data Available\r\n\r\n', '1988-1998, 2007-2010 - Governor of Batanes ', 'REGION II (CAGAYAN VALLEY)', 'BATANES'),
(50, 'Malou Cayco', 'Female', 'Liberal Party', '../pictures/governors/REGION II (CAGAYAN VALLEY)/BATANES/Malou Cayco-02_BATANES_governor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available\r\n\r\n', 'No Data Available\r\n\r\n', '2016-2022 - Governor of Batanes ', 'REGION II (CAGAYAN VALLEY)', 'BATANES'),
(51, 'Manuel Mamba', 'Male', 'Nacionalista Party', '../pictures/governors/REGION II (CAGAYAN VALLEY)/CAGAYAN/Manuel Mamba-02_CAGAYAN_governor.png', 'N/A', 63, '1958-08-19', 'N/A', 'No Data Available\r\n\r\n', 'University of Santo Tomas\r\n\r\n', '1988 - 1995 - Mayor of Tuao | 1995 - 1998, 2001 - 2010 - Member of the Philippine House of Representatives from Cagayan`s 3rd District | 2012 - 2015 - Head of Presidential Legislative Liaison Office | 2016 - 2022 - Governor of Cagayan', 'REGION II (CAGAYAN VALLEY)', 'CAGAYAN'),
(52, 'Dok Zarah Pulsar Lara', 'Female', 'Partido Demokratiko Pilipino Lakas ng Bayan', '../pictures/governors/REGION II (CAGAYAN VALLEY)/CAGAYAN/Dok Zarah Pulsar Lara-02_CAGAYAN_governor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available\r\n\r\n', 'No Data Available\r\n\r\n', 'No Data Available\r\n\r\n', 'REGION II (CAGAYAN VALLEY)', 'CAGAYAN'),
(53, 'Rodolfo Albano III', 'Male', 'Partido Demokratiko Pilipino Lakas ng Bayan', '../pictures/governors/REGION II (CAGAYAN VALLEY)/ISABELA/Rodolfo Albano III-02_ISABELA_governor.png', 'Rodito', 63, '1959-03-02', 'San Pablo, Isabela', 'No Data Available\r\n\r\n', 'Ateneo De Manila University | De La Salle University', '2019-Present – Governor, Isabela | 1998-2001, 2004-2010, 2013-2019 – Congressman, First District of Isabela | 2010-2013 – Vice Governor', 'REGION II (CAGAYAN VALLEY)', 'ISABELA'),
(54, 'Carlos Padilla', 'Male', 'Nacionalista Party', '../pictures/governors/REGION II (CAGAYAN VALLEY)/NUEVA VIZCAYA/Carlos Padilla-02_NUEVA VIZCAYA_governor.png', 'Caloy', 75, '1944-09-19', 'N/A', 'No Data Available\r\n\r\n', 'Polytechnic University of the Philippines', '2016-Present – Governor, Nueva Vizcaya | 1987-1992, 1995-2004, 2007-2016 – Congressman, Nueva Vizcaya | 1978 – Assemblyman, Interim Batasang Pambansa', 'REGION II (CAGAYAN VALLEY)', 'NUEVA VIZCAYA'),
(55, 'Dax Cua', 'Male', 'Pederalismo ng Dugong Dakilang Samahan', '../pictures/governors/REGION II (CAGAYAN VALLEY)/QUIRINO/Dax Cua-02_QUIRINO_governor.png', 'N/A', 0, '0000-00-00', 'Quirino, Philippines', 'No Data Available\r\n\r\n', 'University of the Philippines', '2019-Present – National Chairman, League of Provinces of the Philippines (LPP) | 2007-2010, 2019-Present – Governor | 2010-2019 – Congressman | 2001-2007 – Vice Governor', 'REGION II (CAGAYAN VALLEY)', 'QUIRINO'),
(56, 'Sid Galban ', 'Male', 'Laban ng Demokratikong Pilipino', '../pictures/governors/REGION III (CENTRAL LUZON)/AURORA/Sid Galban -03_AURORA_governor.png', 'N/A', 58, '0000-00-00', 'Baler, Aurora', 'No Data Available\r\n\r\n', 'Philippine Normal University | National University ', '2019-Present - Provincial Board Member, 1st District of Aurora Province ', 'REGION III (CENTRAL LUZON)', 'AURORA'),
(57, 'Atty. Christian Noveras', 'Male', 'Partido Demokratiko Pilipino Lakas ng Bayan ', '../pictures/governors/REGION III (CENTRAL LUZON)/AURORA/Atty. Christian Noveras-03_AURORA_governor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available\r\n\r\n', 'Manuel L. Quezon University', '2020 - Acting Governor\r\n2019-Present - Vice Governor', 'REGION III (CENTRAL LUZON)', 'AURORA'),
(58, 'Jose Enrique Garcia III', 'Male', 'Partido Demokratiko Pilipino Lakas ng Bayan', '../pictures/governors/REGION III (CENTRAL LUZON)/BATAAN/Jose Enrique Garcia III-03_BATAAN_governor.png', 'Joet', 41, '1971-11-12', 'Balanga City, Bataan', 'No Data Available', 'University of Asia and the Pacific', '2019-Present – Vice Chairperson, House Committee on Appropriations | 2019-Present – Vice Chairperson, House Committee on Energy | 2019-Present – Vice Chairperson, House Committee on Health | 2016-Present – Congressman | 2007-2016 – Mayor, Balanga City', 'REGION III (CENTRAL LUZON)', 'BATAAN'),
(59, 'Daniel Fernando', 'Male', 'National Unity Party ', '../pictures/governors/REGION III (CENTRAL LUZON)/BULACAN/Daniel Fernando-03_BULACAN_governor.png', 'N/A', 59, '1962-03-12', 'N/A', 'No Data Available', 'University of the East', '2019-2020 - Governor of Bulacan\r\n2010-2019 - Vice Governor of Bulacan', 'REGION III (CENTRAL LUZON)', 'BULACAN'),
(60, 'Wilhelmino Sy-Alvarado', 'Male', 'Partido Demokratiko Pilipino Lakas ng Bayan', '../pictures/governors/REGION III (CENTRAL LUZON)/BULACAN/Wilhelmino Sy-Alvarado-03_BULACAN_governor.png', 'N/A', 72, '1946-12-29', 'N/A', 'No Data Available', 'University of Santo Tomas | Bulacan State University', '2019-Present – Vice Governor | 2010-2019 – Governor | 1998-2007 – Congressman, First Legislative District of Bulacan | 1987-1998 – Mayor, Hagonoy Municipality', 'REGION III (CENTRAL LUZON)', 'BULACAN'),
(61, 'Rianne Cuevas', 'Male', 'Partido Demokratiko Pilipino Lakas ng Bayan', '../pictures/governors/REGION III (CENTRAL LUZON)/NUEVA ECIJA/Rianne Cuevas-03_NUEVA ECIJA_governor.png', 'Partido Demokratiko Pilipino Lakas ng Bayan', 0, '0000-00-00', 'N/A', 'No Data Available\r\n', 'No Data Available\r\n', '2013-Present - Mayor', 'REGION III (CENTRAL LUZON)', 'NUEVA ECIJA'),
(62, 'Aurelio Umali', 'Male', 'Unang Sigaw', '../pictures/governors/REGION III (CENTRAL LUZON)/NUEVA ECIJA/Aurelio Umali-03_NUEVA ECIJA_governor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available\r\n', 'No Data Available\r\n', 'No Data Available\r\n', 'REGION III (CENTRAL LUZON)', 'NUEVA ECIJA'),
(63, 'Dennis Pineda', 'Male', 'Nationalist People`s Coalition', '../pictures/governors/REGION III (CENTRAL LUZON)/PAMPANGA/Dennis Pineda-03_PAMPANGA_governor.png', 'N/A', 0, '0000-00-00', 'Lubao, Pampanga', 'No Data Available\r\n', 'Guagua National Colleges', '2019-Present – Governor | 2010-2019 – Vice Governor | 2001-2010 – Mayor, Lubao | 1998-2001 – Councilor, Lubao', 'REGION III (CENTRAL LUZON)', 'PAMPANGA'),
(64, 'Danilo Baylon', 'Male', 'Liberal Party', '../pictures/governors/REGION III (CENTRAL LUZON)/PAMPANGA/Danilo Baylon-03_PAMPANGA_governor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'University of Sto. Tomas | San Beda College in Manila | De La Salle University', '2007-2016, 2019-Present – Governor | 2001-2007 – Congressman, 3rd Legislative District', 'REGION III (CENTRAL LUZON)', 'PAMPANGA'),
(65, 'Susan Yap', 'Female', 'Nacionalist People`s Coalition ', '../pictures/governors/REGION III (CENTRAL LUZON)/TARLAC/Susan Yap-03_TARLAC_governor.png', 'N/A', 0, '0000-00-00', 'San Jose, Tarlac', 'No Data Available', 'University of the Philippines Diliman | Ateneo De Manila University | Asian Institute of Management', '2019-Present – Executive Vice President, League of Provinces of the Philippines (LPP) | 2016-Present – Governor | 2010-2016 – Congresswoman', 'REGION III (CENTRAL LUZON)', 'TARLAC'),
(66, 'Cheryl Deloso-Montalla', 'Female', 'Nationalist People`s Coalition', '../pictures/governors/REGION III (CENTRAL LUZON)/ZAMBALES/Cheryl Deloso-Montalla-03_ZAMBALES_governor.png', 'N/A', 52, '1968-10-01', 'Botolan, Zambales', 'No Data Available', 'No Data Available', '2019-Present – Chairperson, House \r\nCommittee on Revision of Laws | 2013-Present – Congresswoman | 2012 – Ran for Congress during the Special Election but lost to Jun Omar Ebdane | 1998-2001 – Vice Governor', 'REGION III (CENTRAL LUZON)', 'ZAMBALES'),
(67, 'Hermogenes  Ebdane Jr.', 'Male', 'Sulong Zambales', '../pictures/governors/REGION III (CENTRAL LUZON)/ZAMBALES/Hermogenes  Ebdane Jr.-03_ZAMBALES_governor.png', 'Jun', 70, '1948-12-30', 'Candelaria, Zambales', 'No Data Available', 'Mapua Institute of Technology | Philippine Military Academy | Philippine College of  Criminology Bicol University', '2010-2016, 2019-Present – Governor | 2005-2009 – Secretary, Department of Public Works and Highways | 2007 – Secretary, National Defense | 2002-2004 – Chief, Philippine National Police', 'REGION III (CENTRAL LUZON)', 'ZAMBALES'),
(68, 'Hermilando Mandanas', 'Male', 'Partido Demokratiko Pilipino Lakas ng Bayan', '../pictures/governors/REGION IV-A (CALABARZON)/BATANGAS/Hermilando Mandanas-04A_BATANGAS_governor.png', 'Dodo Mandanas', 75, '1944-03-25', 'Bauan, Batangas', 'Doctor of Humanities, Batangas State University', 'De La Salle University Manila | University of the Philippines | Batangas State University', '1995-2004, 2016-Present – Governor | 2004-2013 – Congressman', 'REGION IV-A (CALABARZON)', 'BATANGAS'),
(69, 'Prudencio Gutierrez', 'Male', 'Nationalist People`s Coalition', '../pictures/governors/REGION IV-A (CALABARZON)/BATANGAS/Prudencio Gutierrez-04A_BATANGAS_governor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', '2010-2013 - Mayor of Padre Garcia, Batangas', 'REGION IV-A (CALABARZON)', 'BATANGAS'),
(70, 'Juanito Victor Remulla', 'Male', 'National Unit Party', '../pictures/governors/REGION IV-A (CALABARZON)/CAVITE/Juanito Victor Remulla-04A_CAVITE_governor.png', 'Jonvic ', 53, '1967-10-23', 'Imus, Cavite', 'No Data Available', 'University of the Philippines Diliman', '2010-2016, 2019-Present – Governor | 2005, 2006, 2007 – Acting Governor | 1998-2007 – Vice Governor | 1995-1998 – Provincial Board Member', 'REGION IV-A (CALABARZON)', 'CAVITE'),
(71, 'Marisol Aragones', 'Female', 'Nacionalista Party', '../pictures/governors/REGION IV-A (CALABARZON)/LAGUNA/Marisol Aragones-04A_LAGUNA_governor.png', 'Sol', 41, '1977-11-06', 'San Pablo City, Laguna', 'No Data Available', 'University of the Philippines Los Banos', '2019-Present – Chairperson, House Committee on Tourism | 2013-Present – Congresswoman', 'REGION IV-A (CALABARZON)', 'LAGUNA'),
(72, 'Ramil Hernandez', 'Male', 'Partido Demokratiko Pilipino Lakas ng Bayan', '../pictures/governors/REGION IV-A (CALABARZON)/LAGUNA/Ramil Hernandez-04A_LAGUNA_governor.png', 'Ramil', 49, '1972-07-25', 'Calamba City, Laguna', 'No Data Available\r\n\r\n', 'Colegio de San Juan de Letran', '2014-Present – Governor | 2010 – Ran for governor but placed only 4th (Emilio Ramon `ER` Ejercito Won)\r\n| 2007-2010, 2013-2014 – Vice Governor | 2004-2007 – Provincial Board Member | 1995-2004 – Councilor, Calamba City', 'REGION IV-A (CALABARZON)', 'LAGUNA'),
(73, 'Danny Suarez', 'Male', 'Lakas Christian Muslim Democrats', '../pictures/governors/REGION IV-A (CALABARZON)/QUEZON/Danny Suarez-04A_QUEZON_governor.png', 'Dan', 76, '1942-12-20', 'Lucena, Quezon', 'No Data Available\r\n', 'No Data Available\r\n', '2019-Present – Governor\r\n| 2012-2013, 2016-2019 – Minority Floor Leader of the House of Representative\r\n| 1992-2001, 2004-2013, 2016-2019 – Congressman of the 3rd District', 'REGION IV-A (CALABARZON)', 'QUEZON'),
(74, 'Angelina De Luna Tan', 'Female', 'Nationalist People`s Coalition', '../pictures/governors/REGION IV-A (CALABARZON)/QUEZON/Angelina De Luna Tan-04A_QUEZON_governor.png', 'Helen', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', '2019-2020 – Chairperson, House Committee on Health | 2013-Present – Congresswoman', 'REGION IV-A (CALABARZON)', 'QUEZON'),
(75, 'Presby Velasco ', 'Male', 'Partido Demokratiko Pilipino Lakas ng Bayan', '../pictures/governors/REGION IV-B (MIMAROPA)/MARINDUQUE/Presby Velasco -04B_MARINDUQUE_governor.png', 'N/A', 73, '1948-08-08', 'N/A', 'No Data Available', 'University of the Philippines', '2019-Present – National President, League of Provinces of the Philippines | 2019-Present – Governor, Marinduque | 2006-2018 – Associate Justice, Supreme Court | 1998-2001 – Associate Justice of the Philippine Court \r\nof Appeals | 1995-1998 – Undersecretary, Department of Justice', 'REGION IV-B (MIMAROPA)', 'MARINDUQUE'),
(76, 'James Marinduqueño Lim', 'Male', 'Alliance for Barangay Concerns', '../pictures/governors/REGION IV-B (MIMAROPA)/MARINDUQUE/James Marinduqueño Lim-04B_MARINDUQUE_governor.png', 'N/A', 0, '0000-00-00', 'Santa Cruz, Marinduque', 'No Data Available', 'No Data Available', '2013-Present – Vice Governor | January, 2019 – June 30, 2019 – Governor', 'REGION IV-B (MIMAROPA)', 'MARINDUQUE'),
(77, 'Nina Ricci Ynares', 'Female', 'Nationalist People`s Coalition', '../pictures/governors/REGION IV-A (CALABARZON)/RIZAL/Nina Ricci Ynares-04A_RIZAL_governor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'Business Management Degree at De La Salle University, | Attended Law School at San Beda College of Law in 1993-1996', 'No Data Available', 'REGION IV-A (CALABARZON)', 'RIZAL'),
(78, 'Josephine Sato', 'Female', 'Liberal Party', '../pictures/governors/REGION IV-B (MIMAROPA)/OCCIDENTAL MINDORO/Josephine Sato-04B_OCCIDENTAL MINDORO_governor.png', 'Nene', 67, '1954-04-29', 'N/A', 'No Data Available', 'No Data Available', '1988 – 1992 - Vice Governor of Occidental Mindoro\r\n| 1992-2001, 2004-2013 - Governor of Occidental Mindoro | 2001 - 2004, 2013 - 2022 Philippine House of Representatives from Occidental Mindoro`s Lone District', 'REGION IV-B (MIMAROPA)', 'OCCIDENTAL MINDORO'),
(79, 'Eduardo Gadiano', 'Male', 'Partido Demokratiko Pilipino Lakas ng Bayan', '../pictures/governors/REGION IV-B (MIMAROPA)/OCCIDENTAL MINDORO/Eduardo Gadiano-04B_OCCIDENTAL MINDORO_governor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', '2010-2013, 2013-2016, 2016-2019 - Mayor of \r\nSablayan, Mindoro Occidental', 'REGION IV-B (MIMAROPA)', 'OCCIDENTAL MINDORO'),
(80, 'Humerlito Dolor', 'Male', 'Partido Demokratiko Pilipino Lakas ng Bayan', '../pictures/governors/REGION IV-B (MIMAROPA)/ORIENTAL MINDORO/Humerlito Dolor-04B_ORIENTAL MINDORO_governor.png', 'Bonz', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', '2013-2016, 2016-2019 - Vice-Governor of Mindoro Oriental Province | 2010-2013 - Provincial Board Member of Mindoro \r\nOriental Province', 'REGION IV-B (MIMAROPA)', 'ORIENTAL MINDORO'),
(83, 'Paulino Leachon', 'Male', 'Mindoro Bago Sarili Party', '../pictures/governors/REGION IV-B (MIMAROPA)/ORIENTAL MINDORO/Paulino Leachon-04B_ORIENTAL MINDORO_governor.png', 'Doy', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', '2019-February 2020 – Chairman, House of \r\nRepresentatives Electoral Tribunal (HRET) | 2013-Present – Congressman | 2007-2013 – Mayor, Calapan City', 'REGION IV-B (MIMAROPA)', 'ORIENTAL MINDORO'),
(84, 'Dennis Socrates', 'Male', 'Partidong Pagbabago ng Palawan ', '../pictures/governors/REGION IV-B (MIMAROPA)/PALAWAN/Dennis Socrates-04B_PALAWAN_governor.png', 'N/A', 60, '1961-09-21', 'N/A', 'No Data Available', 'University of the Philippines\r\nAteneo De Manila University', '2013-Present – Vice Governor\r\n| 2010-2013 – Congressman, Second District of Palawan', 'REGION IV-B (MIMAROPA)', 'PALAWAN'),
(85, 'Erick Abueg', 'Male', 'Independent', '../pictures/governors/REGION IV-B (MIMAROPA)/PALAWAN/Erick Abueg-04B_PALAWAN_governor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'REGION IV-B (MIMAROPA)', 'PALAWAN'),
(86, 'Otik Riano', 'Male', 'Partido Demokratiko Pilipino Lakas ng Bayan', '../pictures/governors/REGION IV-B (MIMAROPA)/ROMBLON/Otik Riano-04B_ROMBLON_governor.png', 'N/A', 45, '1977-01-09', 'N/A', 'No Data Available', 'No Data Available', '2013-2016 - Vice Governor of Romblon\r\n| 2019-2022 - Governor of Romblon', 'REGION IV-B (MIMAROPA)', 'ROMBLON'),
(87, 'Al Francis Bichara', 'Male', 'Nacionalista Party', '../pictures/governors/REGION V (BICOL REGION)/ALBAY/Al Francis Bichara-05_ALBAY_governor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'REGION V (BICOL REGION)', 'ALBAY'),
(88, 'Noel Rosal', 'Male', 'Katipunan ng Nagkakaisang Pilipino Party (KANP)', '../pictures/governors/REGION V (BICOL REGION)/ALBAY/Noel Rosal-05_ALBAY_governor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'REGION V (BICOL REGION)', 'ALBAY'),
(89, 'Edgardo Tallado', 'Male', 'Partido Demokratiko Pilipino Lakas ng Bayan ', '../pictures/governors/REGION V (BICOL REGION)/CAMARINES NORTE/Edgardo Tallado-05_CAMARINES NORTE_governor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'REGION V (BICOL REGION)', 'CAMARINES NORTE'),
(90, 'Rolando Andaya Jr.', 'Male', 'Nationalist People`s Coalition', '../pictures/governors/REGION V (BICOL REGION)/CAMARINES SUR/Rolando Andaya Jr.-05_CAMARINES SUR_governor.png', 'Nonoy', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'REGION V (BICOL REGION)', 'CAMARINES SUR'),
(91, 'Imelda Papin', 'Female', 'Partido Federal ng Pilipinas', '../pictures/governors/REGION V (BICOL REGION)/CAMARINES SUR/Imelda Papin-05_CAMARINES SUR_governor.png', 'N/A', 66, '1956-01-26', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'REGION V (BICOL REGION)', 'CAMARINES SUR'),
(92, 'Shirley Abundo', 'Female', 'Aksyon Demokratiko', '../pictures/governors/REGION V (BICOL REGION)/CATANDUANES/Shirley Abundo-05_CATANDUANES_governor.png', 'N/A', 0, '0000-00-00', 'Catanduanes, Philippines', 'No Data Available', 'No Data Available', '2016-Present – Vice Governor\r\n| 2018, 2019 – Acting Governor\r\n', 'REGION V (BICOL REGION)', 'CATANDUANES'),
(93, 'Joseph Cua', 'Male', 'National People`s Coalition', '../pictures/governors/REGION V (BICOL REGION)/CATANDUANES/Joseph Cua-05_CATANDUANES_governor.png', 'Boboy', 59, '1962-10-16', 'Catanduanes, Philippines', 'No Data Available', 'College of Business Administration Major in Accounting at Philippine School of Business Administration - 1981–1985', '2001-2004- Mayor of San Andres, Catanduanes\r\n| 2007 – 2010, 2010 – 2013, 2016 – Present - Provincial Governor of Catanduanes  \r\n', 'REGION V (BICOL REGION)', 'CATANDUANES'),
(94, 'Bong Bravo', 'Male', 'National Unity Party ', '../pictures/governors/REGION V (BICOL REGION)/MASBATE/Bong Bravo-05_MASBATE_governor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'REGION V (BICOL REGION)', 'MASBATE'),
(95, 'Jose Edwin Hamor', 'Male', 'Nationalist People`s Coalition ', '../pictures/governors/REGION V (BICOL REGION)/SORSOGON/Jose Edwin Hamor-05_SORSOGON_governor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'REGION V (BICOL REGION)', 'SORSOGON'),
(96, 'Sally Lee', 'Female', 'National Unity Party', '../pictures/governors/REGION V (BICOL REGION)/SORSOGON/Sally Lee-05_SORSOGON_governor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'REGION V (BICOL REGION)', 'SORSOGON'),
(97, 'William Lachica', 'Male', 'Kilusang Bagong Lipunan', '../pictures/governors/REGION VI (WESTERN VISAYAS)/AKLAN/William Lachica-06_AKLAN_governor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', '2019-Present - Mayor', 'REGION VI (WESTERN VISAYAS)', 'AKLAN'),
(98, 'Jose Enrique Miraflores ', 'Male', 'Partido Demokratiko Pilipino Lakas ng Bayan', '../pictures/governors/REGION VI (WESTERN VISAYAS)/AKLAN/Jose Enrique Miraflores -06_AKLAN_governor.png', 'Joen', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', '2010-2013 - Provincial Board Member of Aklan Province', 'REGION VI (WESTERN VISAYAS)', 'AKLAN'),
(99, 'Rhodora Cadio ', 'Female', 'National Unity Party', '../pictures/governors/REGION VI (WESTERN VISAYAS)/ANTIQUE/Rhodora Cadio -06_ANTIQUE_governor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', '2015-Present - Governor\r\n2013-2015, 2004-2010 - Vice Governor', 'REGION VI (WESTERN VISAYAS)', 'ANTIQUE'),
(100, 'Fredenil Castro', 'Male', 'Lakas Christian Muslim Democrats', '../pictures/governors/REGION VI (WESTERN VISAYAS)/CAPIZ/Fredenil Castro-06_CAPIZ_governor.png', 'Oto', 70, '1951-04-27', 'Parañaque, Metro Manila', 'No Data Available', 'Colegio de la Purisima Concepcion | San Beda College', '2001 - 2010, 2013 - 2020 -Member of the\r\nPhilippine House of Representatives\r\nfrom Capiz`s 2nd district | 2016 - 2019 - Deputy Speaker\r\nof the House of Representatives', 'REGION VI (WESTERN VISAYAS)', 'CAPIZ'),
(101, 'Esteban Evan Contreras', 'Male', 'Partido Demokratiko Pilipino Lakas ng Bayan', '../pictures/governors/REGION VI (WESTERN VISAYAS)/CAPIZ/Esteban Evan Contreras-06_CAPIZ_governor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available\r\n', 'University of San Agustin', '2010 - 2019 - Vice Governor of Capiz | 2019 - 2022 - Governor of Capiz', 'REGION VI (WESTERN VISAYAS)', 'CAPIZ'),
(102, 'Arthur Defensor Jr.', 'Male', 'National Unity Party and Uswag Ilonggo', '../pictures/governors/REGION VI (WESTERN VISAYAS)/ILOILO/Arthur Defensor Jr.-06_ILOILO_governor.png', 'Toto', 32, '1969-10-08', 'Mina, Iloilo ', 'No Data Available\r\n', 'University of the Philippines | Ateneo De Manila University', '2019-Present – Governor | 2010-2019 – Congressman, third legislative district of \r\nIloilo | 2007-2010 – Provincial Board Member', 'REGION VI (WESTERN VISAYAS)', 'ILOILO'),
(103, 'Joaquin Carlos Nava', 'Male', 'National Unity Party', '../pictures/governors/REGION VI (WESTERN VISAYAS)/GUIMARAS/Joaquin Carlos Nava-06_GUIMARAS_governor.png', 'Rahman', 59, '1962-11-19', 'N/A', 'No Data Available\r\n', 'No Data Available\r\n', '2007-2010, 2010-2013 -  House Representative of \r\nGuimaras Province', 'REGION VI (WESTERN VISAYAS)', 'GUIMARAS'),
(104, 'Eugenio Jose Lacson', 'Male', 'Nationalist People`s Coalition', '../pictures/governors/REGION VI (WESTERN VISAYAS)/NEGROS OCCIDENTAL/Eugenio Jose Lacson-06_NEGROS OCCIDENTAL_governor.png', 'Bong', 62, '1959-12-13', 'N/A', 'No Data Available\r\n', 'No Data Available\r\n', '2019-Present – Governor | 2010-2019 – Vice Governor | 2001-2010 – Mayor, San Carlos City', 'REGION VI (WESTERN VISAYAS)', 'NEGROS OCCIDENTAL'),
(105, 'Erico Aumentado', 'Male', 'Nationalist People`s Coalition', '../pictures/governors/REGION VII (CENTRAL VISAYAS)/BOHOL/Erico Aumentado-07_BOHOL_governor.png', 'Aris', 44, '1977-12-29', 'N/A', 'No Data Available\r\n', 'No Data Available\r\n', '2013 - 2022 - Member of the Philippine House of \r\nRepresentatives  from Bohol`s 2nd District | 1996 - 2001 - Sangguniang Kabataan', 'REGION VII (CENTRAL VISAYAS)', 'BOHOL'),
(106, 'Arthur Yap', 'Male', 'Partido Demokratiko Pilipino Lakas ng Bayan', '../pictures/governors/REGION VII (CENTRAL VISAYAS)/BOHOL/Arthur Yap-07_BOHOL_governor.png', 'Art', 56, '1965-11-10', 'Pasig', 'No Data Available\r\n', 'Ateneo de Manila University', '2004 - 2005, 2006 - 2010 - Secretary of Agriculture | 2010 - 2019 - Member of the Philippine House of \r\nRepresentatives from Bohol`s Third District', 'REGION VII (CENTRAL VISAYAS)', 'BOHOL'),
(107, 'Gwendolyn Garcia', 'Female', 'PDP Laban/One Cebu', '../pictures/governors/REGION VII (CENTRAL VISAYAS)/CEBU/Gwendolyn Garcia-07_CEBU_governor.png', 'N/A', 66, '1955-10-12', 'N/A', 'No Data Available\r\n', 'University of the Philippines', '2013 - 2019 - Deputy Speaker of the Philippine House of Representatives | 2004-2013, 2019-2022 - Governor of Cebu', 'REGION VII (CENTRAL VISAYAS)', 'CEBU'),
(108, 'Joseph Felix Durano', 'Male', 'Partido Pilipino Pagbabago', '../pictures/governors/REGION VII (CENTRAL VISAYAS)/CEBU/Joseph Felix Durano-07_CEBU_governor.png', 'Ace', 51, '1970-04-03', 'N/A', 'No Data Available\r\n', 'No Data Available\r\n', '2004 - 2010 - Secretary of Tourism | 1998 - 2004, 2013 - 2016 - Member of the\r\nPhilippine House of Representatives from Cebu`s 5th district', 'REGION VII (CENTRAL VISAYAS)', 'CEBU'),
(109, 'Roel Degamo', 'Male', 'Nacionalista Party ', '../pictures/governors/REGION VII (CENTRAL VISAYAS)/NEGROS ORIENTAL/Roel Degamo-07_NEGROS ORIENTAL_governor.png', 'N/A', 55, '1966-04-29', 'N/A', 'No Data Available\r\n', 'Siliman University', '2010 - 2011 - Vice-Governor of Negros Oriental | 2011-2022 - Governor of Negros Oriental', 'REGION VII (CENTRAL VISAYAS)', 'NEGROS ORIENTAL'),
(110, 'Pryde Henry Teves', 'Male', 'Nationalist People`s Coalition', '../pictures/governors/REGION VII (CENTRAL VISAYAS)/NEGROS ORIENTAL/Pryde Henry Teves-07_NEGROS ORIENTAL_governor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available\r\n', 'No Data Available\r\n', '2019-2022 - City Mayor of City Of Bayawan (Tulong) in the \r\nprovince of Negros Oriental', 'REGION VII (CENTRAL VISAYAS)', 'NEGROS ORIENTAL'),
(111, 'Jake Vincent Villa', 'Male', 'Nationalist People`s Coalition', '../pictures/governors/REGION VII (CENTRAL VISAYAS)/SIQUIJOR/Jake Vincent Villa-07_SIQUIJOR_governor.png', 'Jec-Jec', 0, '0000-00-00', 'N/A', 'No Data Available\r\n', 'No Data Available\r\n', 'No Data Available\r\n', 'REGION VII (CENTRAL VISAYAS)', 'SIQUIJOR'),
(112, 'Gerard Roger Espina', 'Male', 'Nacionalista Party', '../pictures/governors/REGION VIII (EASTERN VISAYAS)/BILIRAN/Gerard Roger Espina-08_BILIRAN_governor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available\r\n', 'No Data Available\r\n', 'No Data Available\r\n', 'REGION VIII (EASTERN VISAYAS)', 'BILIRAN'),
(113, 'Ben Evardone', 'Male', 'Partido Demokratiko Pilipino Lakas ng Bayan', '../pictures/governors/REGION VIII (EASTERN VISAYAS)/EASTERN SAMAR/Ben Evardone-08_EASTERN SAMAR_governor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available\r\n', 'No Data Available\r\n', 'No Data Available\r\n', 'REGION VIII (EASTERN VISAYAS)', 'EASTERN SAMAR'),
(114, 'Avit Opiniano', 'Male', 'People`s Reform Party', '../pictures/governors/REGION VIII (EASTERN VISAYAS)/LEYTE/Avit Opiniano-08_LEYTE_governor.png', 'N/A', 0, '0000-00-00', 'Pastrano, Leyte', 'No Data Available\r\n', 'National University | Divine Word University', 'No Data Available\r\n', 'REGION VIII (EASTERN VISAYAS)', 'LEYTE'),
(115, 'Carlos Jericho Petilla', 'Male', 'Partido Demokratiko Pilipino Lakas ng Bayan', '../pictures/governors/REGION VIII (EASTERN VISAYAS)/LEYTE/Carlos Jericho Petilla-08_LEYTE_governor.png', 'Icot', 0, '0000-00-00', 'N/A', 'No Data Available\r\n', 'Ateneo de Manila University', '2004 - 2012 - Governor of Leyte | 2012 - 2015 - Secretary of the Philippine Department of Energy', 'REGION VIII (EASTERN VISAYAS)', 'LEYTE'),
(116, 'Hildegardes Dineros', 'Male', 'Independent', '../pictures/governors/REGION VIII (EASTERN VISAYAS)/NORTHERN SAMAR/Hildegardes Dineros-08_NORTHERN SAMAR_governor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available\r\n', 'No Data Available\r\n', 'No Data Available\r\n', 'REGION VIII (EASTERN VISAYAS)', 'NORTHERN SAMAR'),
(117, 'Edwin Marino Ongchuan', 'Male', 'National Unity Party', '../pictures/governors/REGION VIII (EASTERN VISAYAS)/NORTHERN SAMAR/Edwin Marino Ongchuan-08_NORTHERN SAMAR_governor.png', 'N/A', 54, '1968-03-03', 'Maharlika Highway, Brgy. Rawis, Laoang', 'No Data Available\r\n', 'University of the Philippines', '2019-2022 - Provincial Governor, Northern Samar | 2016-2019 - Member, House of Representatives, 2nd District, Northern Samar', 'REGION VIII (EASTERN VISAYAS)', 'NORTHERN SAMAR'),
(118, 'Sharee Ann Tan', 'Female', 'Nacionalista Party', '../pictures/governors/REGION VIII (EASTERN VISAYAS)/SAMAR (WESTERN SAMAR)/Sharee Ann Tan-08_SAMAR (WESTERN SAMAR)_governor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available\r\n', 'No Data Available\r\n', 'No Data Available\r\n', 'REGION VIII (EASTERN VISAYAS)', 'SAMAR (WESTERN SAMAR)'),
(119, 'Damian Mercado', 'Male', 'Partido Demokratiko', '../pictures/governors/REGION VIII (EASTERN VISAYAS)/SOUTHERN LEYTE/Damian Mercado-08_SOUTHERN LEYTE_governor.png', 'Mian', 67, '1954-11-24', 'Abgao, Maasin City, Southern Leyte', 'No Data Available\r\n', 'No Data Available\r\n', '| 2008-2011, 2012, 2016-Present  - Provincial Governor | 2013-2016 - Congressman | 2000-2007 - City Mayor', 'REGION VIII (EASTERN VISAYAS)', 'SOUTHERN LEYTE'),
(120, 'Evelyn Tang Uy', 'Female', 'Partido Demokratiko Pilipino Lakas ng Bayan', '../pictures/governors/REGION IX (ZAMBOANGA PENINSULA)/ZAMBOANGA DEL NORTE/Evelyn Tang Uy-09_ZAMBOANGA DEL NORTE_governor.png', 'Belen', 0, '0000-00-00', 'N/A', 'No Data Available\r\n', 'No Data Available\r\n', 'No Data Available\r\n', 'REGION IX (ZAMBOANGA PENINSULA)', 'ZAMBOANGA DEL NORTE'),
(121, 'Alex Delos Santos', 'Female', 'Independent', '../pictures/governors/REGION IX (ZAMBOANGA PENINSULA)/ZAMBOANGA DEL SUR/Alex Delos Santos-09_ZAMBOANGA DEL SUR_governor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available\r\n', 'No Data Available\r\n', 'No Data Available\r\n', 'REGION IX (ZAMBOANGA PENINSULA)', 'ZAMBOANGA DEL SUR'),
(122, 'Aurora Cerilles', 'Female', 'Nacionalista Party', '../pictures/governors/REGION IX (ZAMBOANGA PENINSULA)/ZAMBOANGA DEL SUR/Aurora Cerilles-09_ZAMBOANGA DEL SUR_governor.png', 'N/A', 72, '1949-11-17', 'N/A', 'No Data Available\r\n', 'University of the East', '2001 - 2010 - Governor of Zamboanga del Sur | 1998 - 2001, 2010  2019 - Member of the Philippine \r\nHouse of Representatives from Zamboanga del Sur`s \r\nSecond District', 'REGION IX (ZAMBOANGA PENINSULA)', 'ZAMBOANGA DEL SUR'),
(123, 'Dulce Ann Hofer', 'Female', 'Partido Demokratiko Pilipino Lakas ng Bayan', '../pictures/governors/REGION IX (ZAMBOANGA PENINSULA)/ZAMBOANGA SIBUGAY/Dulce Ann Hofer-09_ZAMBOANGA SIBUGAY_governor.png', 'Ann', 0, '0000-00-00', 'N/A', 'No Data Available\r\n', 'No Data Available\r\n', '2019-Present – Chairperson, Committee on Foreign \r\nAffairs (House of Representatives)| 2007-2010, 2013-Present – Congresswoman | 2010 – Ran for governor but lost to Rommel Jalosjos', 'REGION IX (ZAMBOANGA PENINSULA)', 'ZAMBOANGA SIBUGAY'),
(124, 'Wilter Palma II', 'Male', 'Lakas Christian Muslim Democrats', '../pictures/governors/REGION IX (ZAMBOANGA PENINSULA)/ZAMBOANGA SIBUGAY/Wilter Palma II-09_ZAMBOANGA SIBUGAY_governor.png', 'Sharky', 0, '0000-00-00', 'N/A', 'No Data Available\r\n', 'No Data Available\r\n', '2016 - 2022 - Member of the Philippine House of \r\nRepresentatives from Zamboanga Sibugay`s First \r\nDistrict', 'REGION IX (ZAMBOANGA PENINSULA)', 'ZAMBOANGA SIBUGAY'),
(125, 'Rogelio Neil Roque', 'Male', 'People`s Reform Party', '../pictures/governors/REGION X (NORTHERN MINDANAO)/BUKIDNON/Rogelio Neil Roque-10_BUKIDNON_governor.png', 'Oneil', 0, '0000-00-00', 'N/A', 'No Data Available\r\n', 'No Data Available\r\n', 'No Data Available\r\n', 'REGION X (NORTHERN MINDANAO)', 'BUKIDNON'),
(126, 'Manuel Antonio Zubiri', 'Male', 'Bukidnon Paglaum Party', '../pictures/governors/REGION X (NORTHERN MINDANAO)/BUKIDNON/Manuel Antonio Zubiri-10_BUKIDNON_governor.png', 'Manny', 57, '1964-07-05', 'N/A', 'No Data Available\r\n', 'No Data Available\r\n', '2016-Present - Congressman', 'REGION X (NORTHERN MINDANAO)', 'BUKIDNON'),
(127, 'Periolo Banaag', 'Male', 'Partido Federal ng Pilipinas', '../pictures/governors/REGION X (NORTHERN MINDANAO)/CAMIGUIN/Periolo Banaag-10_CAMIGUIN_governor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available\r\n', 'No Data Available\r\n', '2010-2013 - Provincial Board Member of Camiguin \r\nProvince', 'REGION X (NORTHERN MINDANAO)', 'CAMIGUIN'),
(128, 'Imelda Dimaporo', 'Female', 'Partido Demokratiko Pilipino Lakas ng Bayan', '../pictures/governors/REGION X (NORTHERN MINDANAO)/LANAO DEL NORTE/Imelda Dimaporo-10_LANAO DEL NORTE_governor.png', 'Angging', 63, '1959-01-15', 'N/A', 'No Data Available\r\n', 'Philippine Women`s University', '2010 - 2016 - Member of House of Representatives \r\nfrom Lanao del Norte, 1st District | 2016 - 2022 - Governor of Lanao del Norte', 'REGION X (NORTHERN MINDANAO)', 'LANAO DEL NORTE'),
(129, 'Henry Oaminal ', 'Male', 'Nacionalista Party', '../pictures/governors/REGION X (NORTHERN MINDANAO)/MISAMIS OCCIDENTAL/Henry Oaminal -10_MISAMIS OCCIDENTAL_governor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available\r\n', 'No Data Available\r\n', '2013-2016 - House of Representative member in the \r\n2nd District of Misamis Occidental Province | 2010-2013 - Vice-Governor of Misamis Occidental \r\nProvince', 'REGION X (NORTHERN MINDANAO)', 'MISAMIS OCCIDENTAL'),
(130, 'Oscar Morena', 'Male', 'Abag Promdi', '../pictures/governors/REGION X (NORTHERN MINDANAO)/MISAMIS ORIENTAL/Oscar Morena-10_MISAMIS ORIENTAL_governor.png', 'Oca', 70, '1951-02-28', 'Cagayan De oro  City, Misamis Oriental', 'No Data Available\r\n', 'University of Manila | San Beda College', '2013-Present–Mayor | 2004-2013–Governor | 1998-2004– Congressman', 'REGION X (NORTHERN MINDANAO)', 'MISAMIS ORIENTAL'),
(131, 'Edwin Jubahib', 'Male', 'Partido Para sa Demokratikong Reporma', '../pictures/governors/REGION XI (DAVAO REGION)/DAVAO DEL NORTE/Edwin Jubahib-11_DAVAO DEL NORTE_governor.png', 'Kuya Edwin', 0, '0000-00-00', 'N/A', 'No Data Available\r\n', 'University of Mindanao, Davao City', 'No Data Available\r\n', 'REGION XI (DAVAO REGION)', 'DAVAO DEL NORTE'),
(132, 'Carl Jason Rama', 'Male', 'Hugpong ng Pagbabago', '../pictures/governors/REGION XI (DAVAO REGION)/DAVAO DEL SUR/Carl Jason Rama-11_DAVAO DEL SUR_governor.png', 'N/A', 0, '0000-00-00', 'Kiblawan, Davao Del Sur', 'No Data Available\r\n', 'No Data Available\r\n', '2019-Present', 'REGION XI (DAVAO REGION)', 'DAVAO DEL SUR'),
(133, 'Corazon Malanyaon ', 'Female', 'Nacionalista Party ', '../pictures/governors/REGION XI (DAVAO REGION)/DAVAO ORIENTAL/Corazon Malanyaon -11_DAVAO ORIENTAL_governor.png', 'Cora', 72, '1949-08-22', 'N/A', 'No Data Available\r\n', 'Ateneo de Davao University', '1986 - 1987, 1988 - 1992 - Member of the Davao City Council from the 3rd district | 2007 - 2016 - Governor of Davao Oriental | 2001 - 2007, 2016 - 2022, Member of the Philippine \r\nHouse of Representatives from Davao Oriental`s 1st \r\ndistrict', 'REGION XI (DAVAO REGION)', 'DAVAO ORIENTAL'),
(134, 'Franklin Peralta', 'Male', 'Lakas Christian Muslim Democrats', '../pictures/governors/REGION XI (DAVAO REGION)/DAVAO OCCIDENTAL/Franklin Peralta-11_DAVAO OCCIDENTAL_governor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available\r\n', 'No Data Available\r\n', '2016-2019 - Provincial Vice Governor of Davao \r\nOccidental | 2007-2010, 2010-2013, 2013-2016 - House \r\nRepresentative of Davao Del Sur', 'REGION XI (DAVAO REGION)', 'DAVAO OCCIDENTAL'),
(135, 'Nancy Catamco', 'Female', 'Partido Demokratiko Pilipino Lakas ng Bayan', '../pictures/governors/REGION XII (SOCCSKSARGEN)/COTABATO (NORTH COTABATO)/Nancy Catamco-12_COTABATO (NORTH COTABATO)_governor.png', 'Nancy', 52, '1969-06-19', 'N/A', 'No Data Available\r\n', 'Ateneo de Davao University', '2019-Present – Governor, Cotabato | 2010-2019 – Congresswoman, 2nd District of Cotabato', 'REGION XII (SOCCSKSARGEN)', 'COTABATO (NORTH COTABATO)'),
(136, 'Emmylou Mendoza', 'Female', 'Nacionalista Party', '../pictures/governors/REGION XII (SOCCSKSARGEN)/COTABATO (NORTH COTABATO)/Emmylou Mendoza-12_COTABATO (NORTH COTABATO)_governor.png', 'Lala', 50, '1972-02-25', 'N/A', 'No Data Available\r\n', 'Ateneo de Davao University', '2001 - 2010 - Member of the Philippine House of Representatives from Cotabato`s First District | 2010-2019 - Governor of Cotabato | 2019-2022 - Vice Governor of Cotabato', 'REGION XII (SOCCSKSARGEN)', 'COTABATO (NORTH COTABATO)'),
(137, 'Rogelio Pacquiao', 'Male', 'People`s Champ Movement', '../pictures/governors/REGION XII (SOCCSKSARGEN)/SARANGANI/Rogelio Pacquiao-12_SARANGANI_governor.png', 'Ruel', 39, '1982-06-17', 'Glan, Sarangani', 'No Data Available\r\n', 'Ramon Magsaysay Memorial Colleges | Southwestern University in Cebu City', '2020-Present – Deputy House Speaker | 2016-Present – Congressman | 2007-2015 – Barangay Chairman, Apopong, General \r\nSantos City', 'REGION XII (SOCCSKSARGEN)', 'SARANGANI'),
(138, 'Reynaldo Tamayo Jr.', 'Male', 'Partido Federal ng Pilipinas', '../pictures/governors/REGION XII (SOCCSKSARGEN)/SOUTH COTABATO/Reynaldo Tamayo Jr.-12_SOUTH COTABATO_governor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available\r\n', 'No Data Available\r\n', '2010 - 2019 - Mayor of Tupi, South Cotabato | 2019 - 2022 - Governor of South Cotabato', 'REGION XII (SOCCSKSARGEN)', 'SOUTH COTABATO'),
(139, 'Datu Pax Ali Mangudadatu', 'Male', 'Lakas Christian Muslim Democrats', '../pictures/governors/REGION XII (SOCCSKSARGEN)/SULTAN KUDARAT/Datu Pax Ali Mangudadatu-12_SULTAN KUDARAT_governor.png', 'Omar Pax Mangugudatu', 0, '0000-00-00', 'N/A', 'No Data Available\r\n', 'No Data Available\r\n', '1998 - 2007, 2016 - 2019 - Governor of Sultan Kudarat | 2007 - 2010 - Member of the Philippine House of \r\nRepresentatives from Sultan Kudarat`s First District', 'REGION XII (SOCCSKSARGEN)', 'SULTAN KUDARAT'),
(140, 'Ma. Angelica Amante', 'Female', 'Partido Demokratiko Pilipino Lakas ng Bayan', '../pictures/governors/REGION XIII (CARAGA)/AGUSAN DEL NORTE/Ma. Angelica Amante-13_AGUSAN DEL NORTE_governor.png', 'Angel', 49, '1970-04-16', 'Cabadbaran City, Agusan  del Norte', 'No Data Available\r\n', 'Trinity University of Asia | Father Saturnino Urios University in Butuan', '2004-2007, 2010-2013, 2019-Present – Congresswoman | 1995-2004, 2013-2019 – Governor, Agusan del Norte', 'REGION XIII (CARAGA)', 'AGUSAN DEL NORTE'),
(141, 'Santiago Cane Jr. ', 'Male', 'National Unity Party', '../pictures/governors/REGION XIII (CARAGA)/AGUSAN DEL SUR/Santiago Cane Jr. -13_AGUSAN DEL SUR_governor.png', 'Santi', 0, '0000-00-00', 'N/A', 'No Data Available\r\n', 'Urios College in Butuan City', '2019-Present – Governor\r\n| 2016-2019 – Provincial Board Member, 1st District of \r\nAgusan Del Sur | 2007-2016 – Vice Governor | 1998-2007 – Provincial Board Member, 1st District of \r\nAgusan Del Sur', 'REGION XIII (CARAGA)', 'AGUSAN DEL SUR'),
(142, 'Arlene Bag-ao', 'Female', 'Liberal Party', '../pictures/governors/REGION XIII (CARAGA)/DINAGAT ISLANDS/Arlene Bag-ao-13_DINAGAT ISLANDS_governor.png', 'Kaka', 52, '1969-07-03', 'Loreto, Dinagat Island', 'No Data Available', 'De La Salle University | Ateneo de Manila University', '\"2019-Present – Governor, Dinagat Island\r\n2013-2019 – Congresswoman, Dinagat Island Lone \r\nLegislative District | 2010-2013 – Party-List Representative of AKBAYAN | 2004 – Special Consultant, Secretary of the Department \r\nof Agrarian Reform', 'REGION XIII (CARAGA)', 'DINAGAT ISLANDS'),
(143, 'Francisco Matugas', 'Male', 'Partido Demokratiko Pilipino Lakas ng Bayan', '../pictures/governors/REGION XIII (CARAGA)/SURIGAO DEL NORTE/Francisco Matugas-13_SURIGAO DEL NORTE_governor.png', 'Lalo Matugas', 79, '1942-05-10', 'N/A', 'No Data Available\r\n', 'No Data Available\r\n', '2007 - 2016 - Member of the Philippine House of \r\nRepresentatives from Surigao del Norte`s 1st District\r\n| 1992 - 2001, 2019 - 2022 - Governor of Surigao del \r\nNorte', 'REGION XIII (CARAGA)', 'SURIGAO DEL NORTE'),
(144, 'Robert Lyndon Barbers', 'Male', 'Nacionalista Party', '../pictures/governors/REGION XIII (CARAGA)/SURIGAO DEL NORTE/Robert Lyndon Barbers-13_SURIGAO DEL NORTE_governor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available\r\n', 'No Data Available\r\n', 'No Data Available\r\n', 'REGION XIII (CARAGA)', 'SURIGAO DEL NORTE'),
(145, 'Alexander Pimentel', 'Male', 'Partido Demokratiko Pilipino Lakas ng Bayan', '../pictures/governors/REGION XIII (CARAGA)/SURIGAO DEL SUR/Alexander Pimentel-13_SURIGAO DEL SUR_governor.png', 'Ayec', 0, '0000-00-00', 'N/A', 'No Data Available\r\n', 'No Data Available\r\n', '2019-Present – Governor | 2007-2013, 2016-2019 – Mayor, Tandag', 'REGION XIII (CARAGA)', 'SURIGAO DEL SUR'),
(146, 'Alfiya Akbar', 'Female', 'Lakas Christian Muslim Democrats', '../pictures/governors/BANGSAMORO AUTONOMOUS REGION IN MUSLIM MINDANAO (BARMM)/BASILAN/Alfiya Akbar-BARMM_BASILAN_governor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available\r\n', 'No Data Available\r\n', 'No Data Available\r\n', 'BANGSAMORO AUTONOMOUS REGION IN MUSLIM MINDANAO (BARMM)', 'BASILAN'),
(147, 'Camar Banocag Jr', 'Male', 'Independent', '../pictures/governors/BANGSAMORO AUTONOMOUS REGION IN MUSLIM MINDANAO (BARMM)/LANAO DEL SUR/Camar Banocag Jr-BARMM_LANAO DEL SUR_governor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available\r\n', 'No Data Available\r\n', 'No Data Available\r\n', 'BANGSAMORO AUTONOMOUS REGION IN MUSLIM MINDANAO (BARMM)', 'LANAO DEL SUR'),
(148, 'Gapor Usman', 'Male', 'Reform PH People`s Party', '../pictures/governors/BANGSAMORO AUTONOMOUS REGION IN MUSLIM MINDANAO (BARMM)/LANAO DEL SUR/Gapor Usman-BARMM_LANAO DEL SUR_governor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available\r\n', 'No Data Available\r\n', 'No Data Available\r\n', 'BANGSAMORO AUTONOMOUS REGION IN MUSLIM MINDANAO (BARMM)', 'LANAO DEL SUR'),
(149, 'Esmael Mangudadatu', 'Male', 'United Bangsomoro Justice Party', '../pictures/governors/BANGSAMORO AUTONOMOUS REGION IN MUSLIM MINDANAO (BARMM)/MAGUINDANAO/Esmael Mangudadatu-BARMM_MAGUINDANAO_governor.png', 'Toto', 53, '1968-08-15', 'Buluan Maguindanao', 'No Data Available\r\n', 'University of Mindanao ', '1998 - 2007 - Mayor of Buluan, Maguindanao | 2007 - 2010 - Vice Mayor of Buluan, Maguindanao | 2010 - 2019 - Governor of Maguindanao | 2019 - 2022 - Member of the Philippine House of Representatives\r\nfrom Maguindanao`s 2nd district', 'BANGSAMORO AUTONOMOUS REGION IN MUSLIM MINDANAO (BARMM)', 'MAGUINDANAO'),
(150, 'Abdusakur Tan', 'Male', 'Partido Demokratiko Pilipino Lakas ng Bayan', '../pictures/governors/BANGSAMORO AUTONOMOUS REGION IN MUSLIM MINDANAO (BARMM)/SULU/Abdusakur Tan-BARMM_SULU_governor.png', 'Sakur', 71, '1950-07-13', 'N/A', 'No Data Available\r\n', 'Notre Dame of Jolo College', '1981-1987, 1987-1992 -  Member of the Municipal \r\nCouncil of Jolo | 1996-2001 - Member of the Philippine House of Representatives from the First District of Sulu | 2007 - 2013, 2019 - 2022 - Governor of Sulu | 2013 - 2016 - Vice Governor of Sulu', 'BANGSAMORO AUTONOMOUS REGION IN MUSLIM MINDANAO (BARMM)', 'SULU'),
(151, 'Sadikul Adalla Sahali', 'Male', 'Partido Demokratiko Pilipino Lakas ng Bayan', '../pictures/governors/BANGSAMORO AUTONOMOUS REGION IN MUSLIM MINDANAO (BARMM)/TAWI-TAWI/Sadikul Adalla Sahali-BARMM_TAWI-TAWI_governor.png', 'N/A', 80, '1941-06-18', 'N/A', 'No Available Data', 'Mindanao Agricultural College', '1971 - 1987, 1988 - 1995 - Mayor of Balimbing\r\n| 1998 - 2001, 2004 - 2013 - Governor of Tawi-Tawi', 'BANGSAMORO AUTONOMOUS REGION IN MUSLIM MINDANAO (BARMM)', 'TAWI-TAWI');

-- --------------------------------------------------------

--
-- Table structure for table `mayor_candidates`
--

CREATE TABLE `mayor_candidates` (
  `id` int(255) NOT NULL,
  `candidate` varchar(255) NOT NULL,
  `sex` varchar(255) NOT NULL,
  `partylist` varchar(255) NOT NULL,
  `picture_dir` text NOT NULL,
  `nickname` varchar(255) NOT NULL,
  `age` int(255) NOT NULL,
  `birthdate` date NOT NULL,
  `hometown` varchar(255) NOT NULL,
  `honorary_degree` text NOT NULL,
  `tertiary` text NOT NULL,
  `political_background` text NOT NULL,
  `regions` varchar(255) NOT NULL,
  `provinces` varchar(255) NOT NULL,
  `city_or_municipalities` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `mayor_candidates`
--

INSERT INTO `mayor_candidates` (`id`, `candidate`, `sex`, `partylist`, `picture_dir`, `nickname`, `age`, `birthdate`, `hometown`, `honorary_degree`, `tertiary`, `political_background`, `regions`, `provinces`, `city_or_municipalities`) VALUES
(25, 'Onofre Abad', 'Male', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FIRST DISTRICT/CITY OF MANILA/Onofre Abad-NCR_NCR, FIRST DISTRICT_CITY OF MANILA_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Available Data ', 'No Available Data ', 'No Available Data ', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FIRST DISTRICT', 'CITY OF MANILA'),
(26, 'Amado Bagatsing ', 'Male', 'Kabalikat ng Bayan sa Kaunlaran (KABAKA)', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FIRST DISTRICT/CITY OF MANILA/Amado Bagatsing -NCR_NCR, FIRST DISTRICT_CITY OF MANILA_mayor.png', 'N/A', 74, '1947-12-03', 'N/A', 'No Available Data ', 'No Available Data ', 'No Available Data ', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FIRST DISTRICT', 'CITY OF MANILA'),
(27, 'Elmer Jamias', 'Male', 'People`s Reform Party ', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FIRST DISTRICT/CITY OF MANILA/Elmer Jamias-NCR_NCR, FIRST DISTRICT_CITY OF MANILA_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Available Data ', 'No Available Data ', 'No Available Data ', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FIRST DISTRICT', 'CITY OF MANILA'),
(28, 'Honey Lacuna ', 'Female', 'Asenso Manileño Movement / Aksyon Demokratiko', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FIRST DISTRICT/CITY OF MANILA/Honey Lacuna -NCR_NCR, FIRST DISTRICT_CITY OF MANILA_mayor.png', 'Honey', 56, '1965-05-06', 'N/A', 'No Data Available', 'BS Biology, University of Santo Tomas\r\n', 'Vice Mayor, Manila, 2016-Present | Director, Manila Social Welfare Department, 2013-2015 | Councilor, Manila 4th District, 2004-2013 ', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FIRST DISTRICT', 'CITY OF MANILA'),
(29, 'Christy Lim', 'Female', 'Partido Para sa Demokratikong Reporma', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FIRST DISTRICT/CITY OF MANILA/Christy Lim-NCR_NCR, FIRST DISTRICT_CITY OF MANILA_mayor.png', 'Christy ', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FIRST DISTRICT', 'CITY OF MANILA'),
(30, 'Alex Lopez', 'Male', 'Partido Federal ng Pilipinas', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FIRST DISTRICT/CITY OF MANILA/Alex Lopez-NCR_NCR, FIRST DISTRICT_CITY OF MANILA_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available\r\n', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FIRST DISTRICT', 'CITY OF MANILA'),
(31, 'Ben Abalos', 'Male', 'Partido Demokratiko Pilipino Lakas ng Bayan', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, SECOND DISTRICT/CITY OF MANDALUYONG/Ben Abalos-NCR_NCR, SECOND DISTRICT_CITY OF MANDALUYONG_mayor.png', 'Chairman Ben', 86, '1935-09-21', 'Pangasinan', 'No Available Data', 'AB Economics, Ateneo de Manila University | Bachelor of Laws, Manuel L. Quezon University', 'Officer-in-Charge Mayor of Mandaluyong, 1986–1987\r\nChairman of the Metropolitan Manila Development Authority,\r\n2001–2002 | COMELEC Chairman, 2002–2007', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, SECOND DISTRICT', 'CITY OF MANDALUYONG'),
(32, 'Florencio Solomon', 'Male', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, SECOND DISTRICT/CITY OF MANDALUYONG/Florencio Solomon-NCR_NCR, SECOND DISTRICT_CITY OF MANDALUYONG_mayor.png', 'Ricky', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, SECOND DISTRICT', 'CITY OF MANDALUYONG'),
(33, 'Bayani Fernando ', 'Male', 'Nationalist People`s Coalition ', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, SECOND DISTRICT/CITY OF MARIKINA/Bayani Fernando -NCR_NCR, SECOND DISTRICT_CITY OF MARIKINA_mayor.png', 'Bayani, BF', 75, '1946-07-25', 'San Juan del Monte, Rizal', 'Doctor of Humanities, Ateneo de Cagayan | Doctor of the Public Administration, Polytechnic \r\nUniversity of the Philippines', 'BS Mechanical Engineering, Mapua Institute of Technology | Manager`s Course (MC) for Small-Scale Industries, UP \r\nInstitute for Small-Scale Industries', 'Chairperson, Committee on Human Rights, 2019-present | President, Metro Manila Mayor`s League, 2000-2001', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, SECOND DISTRICT', 'CITY OF MARIKINA'),
(34, 'Marcy Teodoro', 'Male', 'United Nationalist Alliance', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, SECOND DISTRICT/CITY OF MARIKINA/Marcy Teodoro-NCR_NCR, SECOND DISTRICT_CITY OF MARIKINA_mayor.png', 'N/A', 51, '1970-08-02', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, SECOND DISTRICT', 'CITY OF MARIKINA'),
(35, 'Iyo Caruncho Bernardo', 'Male', 'People`s Reform Party', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, SECOND DISTRICT/CITY OF PASIG/Iyo Caruncho Bernardo-NCR_NCR, SECOND DISTRICT_CITY OF PASIG_mayor.png', 'Iyo, Christian', 50, '1971-06-25', 'Pasig City', 'No Data Available', 'BA Mass Communications: Trinity College | MA in Public Management (Currently Enrolled), Ateneo de Manila University', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, SECOND DISTRICT', 'CITY OF PASIG'),
(36, 'Vico Sotto ', 'Male', 'Aksyon Demokratiko', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, SECOND DISTRICT/CITY OF PASIG/Vico Sotto -NCR_NCR, SECOND DISTRICT_CITY OF PASIG_mayor.png', 'Vico', 32, '1989-06-17', 'Pasig City ', 'No Data Available', 'AB Political Science, Ateneo de Manila University | Masters in Public Administration, Ateneo School of Government', 'Executive Board Member, Government Watch, Inc.- present | Mayor, Pasig City- 2019-present – | Councilor, Pasig City - 2016-2019 | Legislative Staff officer V, Quezon City - 2013-2015', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, SECOND DISTRICT', 'CITY OF PASIG'),
(37, 'Glenda Araneta', 'Female', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, SECOND DISTRICT/QUEZON CITY/Glenda Araneta-NCR_NCR, SECOND DISTRICT_QUEZON CITY_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, SECOND DISTRICT', 'QUEZON CITY'),
(38, 'Ricardo Bello ', 'Male', 'Partido Demokratiko  Sosyalista ng Pilipinas', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, SECOND DISTRICT/QUEZON CITY/Ricardo Bello -NCR_NCR, SECOND DISTRICT_QUEZON CITY_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, SECOND DISTRICT', 'QUEZON CITY'),
(39, 'Joy Belmonte', 'Female', 'Serbisyo sa Bayan Party ', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, SECOND DISTRICT/QUEZON CITY/Joy Belmonte-NCR_NCR, SECOND DISTRICT_QUEZON CITY_mayor.png', 'N/A', 51, '1970-03-15', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, SECOND DISTRICT', 'QUEZON CITY'),
(40, 'Michael Defensor', 'Male', 'Partido Federal ng Pilipinas', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, SECOND DISTRICT/QUEZON CITY/Michael Defensor-NCR_NCR, SECOND DISTRICT_QUEZON CITY_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, SECOND DISTRICT', 'QUEZON CITY'),
(41, 'Jose Feliciano Ingles Jr. ', 'Male', 'Workers and Peasants Party AKA Labor Party Philippines', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, SECOND DISTRICT/QUEZON CITY/Jose Feliciano Ingles Jr. -NCR_NCR, SECOND DISTRICT_QUEZON CITY_mayor.png', 'Inventor Jose', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, SECOND DISTRICT', 'QUEZON CITY'),
(42, 'Rolando Jota', 'Male', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, SECOND DISTRICT/QUEZON CITY/Rolando Jota-NCR_NCR, SECOND DISTRICT_QUEZON CITY_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, SECOND DISTRICT', 'QUEZON CITY'),
(43, 'Emma Orozco', 'Female', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, SECOND DISTRICT/QUEZON CITY/Emma Orozco-NCR_NCR, SECOND DISTRICT_QUEZON CITY_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, SECOND DISTRICT', 'QUEZON CITY'),
(44, 'Tom Salutan', 'Male', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, SECOND DISTRICT/QUEZON CITY/Tom Salutan-NCR_NCR, SECOND DISTRICT_QUEZON CITY_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, SECOND DISTRICT', 'QUEZON CITY'),
(45, 'Diosdado Velasco', 'Male', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, SECOND DISTRICT/QUEZON CITY/Diosdado Velasco-NCR_NCR, SECOND DISTRICT_QUEZON CITY_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, SECOND DISTRICT', 'QUEZON CITY'),
(46, 'Jun Usman', 'Male', 'Pwersa ng Masang Pilipino', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, SECOND DISTRICT/CITY OF SAN JUAN/Jun Usman-NCR_NCR, SECOND DISTRICT_CITY OF SAN JUAN_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', '2013-2016 – Barangay Kagawad', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, SECOND DISTRICT', 'CITY OF SAN JUAN'),
(47, 'Francis Zamora', 'Male', 'Partido Demokratiko Pilipino Lakas ng Bayan', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, SECOND DISTRICT/CITY OF SAN JUAN/Francis Zamora-NCR_NCR, SECOND DISTRICT_CITY OF SAN JUAN_mayor.png', 'Francis', 42, '1977-12-05', 'San Juan City, Metro Manila', 'No Data Available', 'De La Salle University (DLSU)', '2019-Present – Mayor | 2016 – Ran for Mayor but lost to Guia Gomez by a small margin | 2010-2016 – Vice Mayor | 2007–2010 – Councilor', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, SECOND DISTRICT', 'CITY OF SAN JUAN'),
(48, 'Jun Anquilan', 'Male', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, THIRD DISTRICT/CALOOCAN CITY/Jun Anquilan-NCR_NCR, THIRD DISTRICT_CALOOCAN CITY_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, THIRD DISTRICT', 'CALOOCAN CITY'),
(49, 'Ruffy Bay-on', 'Male', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, THIRD DISTRICT/CALOOCAN CITY/Ruffy Bay-on-NCR_NCR, THIRD DISTRICT_CALOOCAN CITY_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, THIRD DISTRICT', 'CALOOCAN CITY'),
(50, 'Roman Domasig Jr.', 'Male', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, THIRD DISTRICT/CALOOCAN CITY/Roman Domasig Jr.-NCR_NCR, THIRD DISTRICT_CALOOCAN CITY_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, THIRD DISTRICT', 'CALOOCAN CITY'),
(51, 'Egay Erice', 'Male', 'Aksyon Demokratiko ', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, THIRD DISTRICT/CALOOCAN CITY/Egay Erice-NCR_NCR, THIRD DISTRICT_CALOOCAN CITY_mayor.png', 'Egay', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, THIRD DISTRICT', 'CALOOCAN CITY'),
(52, 'Dale Malapitan', 'Male', 'Partido Demokratiko Pilipino Laks ng Bayan', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, THIRD DISTRICT/CALOOCAN CITY/Dale Malapitan-NCR_NCR, THIRD DISTRICT_CALOOCAN CITY_mayor.png', 'Along', 42, '1979-10-31', 'Caloocon City, Metro Manila', 'Degree - Management', 'Colegio de San Juan de Letran', '2020-Present – Head, House of Representatives Electoral Tribunal | 2019-Present – Vice Chairperson, House Committee on Disaster\r\n Management | 2019-Present – Vice Chairperson, House Committee on Transportation | 2019-2020 – Chairperson, House Committee on Poverty Alleviation | 2016-Present – Congressman | 2013-2016 – Barangay Captain and President, Liga ng mga Barangay \r\nsa Caloocan City', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, THIRD DISTRICT', 'CALOOCAN CITY'),
(53, 'Toto Malunes', 'Male', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, THIRD DISTRICT/CALOOCAN CITY/Toto Malunes-NCR_NCR, THIRD DISTRICT_CALOOCAN CITY_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, THIRD DISTRICT', 'CALOOCAN CITY'),
(54, 'Enzo Oreta', 'Male', 'National Unity Party ', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, THIRD DISTRICT/CITY OF MALABON/Enzo Oreta-NCR_NCR, THIRD DISTRICT_CITY OF MALABON_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, THIRD DISTRICT', 'CITY OF MALABON'),
(55, 'Jeannie Sandoval', 'Female', 'Nacionalista Party', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, THIRD DISTRICT/CITY OF MALABON/Jeannie Sandoval-NCR_NCR, THIRD DISTRICT_CITY OF MALABON_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, THIRD DISTRICT', 'CITY OF MALABON'),
(56, 'Mario Camacho ', 'Male', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, THIRD DISTRICT/CITY OF NAVOTAS/Mario Camacho -NCR_NCR, THIRD DISTRICT_CITY OF NAVOTAS_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, THIRD DISTRICT', 'CITY OF NAVOTAS'),
(57, 'Raymond Alonzo Cruz', 'Male', 'Aksyon Demokratiko', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, THIRD DISTRICT/CITY OF NAVOTAS/Raymond Alonzo Cruz-NCR_NCR, THIRD DISTRICT_CITY OF NAVOTAS_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, THIRD DISTRICT', 'CITY OF NAVOTAS'),
(58, 'John Rey Tiangco', 'Male', 'Partido Naviteño', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, THIRD DISTRICT/CITY OF NAVOTAS/John Rey Tiangco-NCR_NCR, THIRD DISTRICT_CITY OF NAVOTAS_mayor.png', 'John Rey', 49, '1972-11-21', 'Navotas, Metro Manila', 'Bachelor of Science in Accounting | Bachelor of Arts in History', '2000, College of Saint Benilde | 1995, De La Salle University', 'Congressman:\r\n2019 – Present, Representative, Lone District of Navotas City\r\n\r\n| Mayor:   \r\n2016 – 2019, City of Navotas\r\n2013 – 2016, City of Navotas\r\n2010 – 2013, City of Navotas', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, THIRD DISTRICT', 'CITY OF NAVOTAS'),
(59, 'Bombit Bernardo ', 'Male', 'Lingkod ng Mamayan ng Valenzuela City', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, THIRD DISTRICT/CITY OF VALENZUELA/Bombit Bernardo -NCR_NCR, THIRD DISTRICT_CITY OF VALENZUELA_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, THIRD DISTRICT', 'CITY OF VALENZUELA'),
(60, 'Weslie Gatchalian', 'Male', 'Nationalist People`s Coalition', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, THIRD DISTRICT/CITY OF VALENZUELA/Weslie Gatchalian-NCR_NCR, THIRD DISTRICT_CITY OF VALENZUELA_mayor.png', 'Wes', 41, '1980-08-11', 'Valenzuela City, Metro Manila', 'Degree – Business and Operations Management', 'College – Bryant College, Rhode Island, USA | College – Oxford Brookes University, Oxford, \r\nUnited Kingdom | Master – London Metropolitan University, London, \r\nUnited Kingdom', '2020-Present – Deputy House Speaker | 2019-2020 – Chairperson, House Committee on Trade and Industry | 2016-Present – Congressman', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, THIRD DISTRICT', 'CITY OF VALENZUELA'),
(61, 'Antonio Abellar Jr.', 'Male', 'Partido Maharlika', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/CITY OF LAS PIÑAS/Antonio Abellar Jr.-NCR_NCR, FOURTH DISTRICT_CITY OF LAS PIÑAS_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'CITY OF LAS PIÑAS'),
(62, 'Imelda Aguilar', 'Female', 'Nacionalista Party', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/CITY OF LAS PIÑAS/Imelda Aguilar-NCR_NCR, FOURTH DISTRICT_CITY OF LAS PIÑAS_mayor.png', 'Mel', 75, '1946-10-31', 'Las Piñas CIty, Metro Manila', 'No Data Available', 'No Data Available', '2019-2022 – Mayor | 2016-2019 – Mayor | 2004-2007 – Mayor', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'CITY OF LAS PIÑAS'),
(63, 'Louie Casimiro ', 'Male', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/CITY OF LAS PIÑAS/Louie Casimiro -NCR_NCR, FOURTH DISTRICT_CITY OF LAS PIÑAS_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'CITY OF LAS PIÑAS'),
(64, 'Aladin De Jesus', 'Male', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/CITY OF LAS PIÑAS/Aladin De Jesus-NCR_NCR, FOURTH DISTRICT_CITY OF LAS PIÑAS_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'CITY OF LAS PIÑAS'),
(65, 'Ferdinand Camigla Eusebio', 'Male', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/CITY OF LAS PIÑAS/Ferdinand Camigla Eusebio-NCR_NCR, FOURTH DISTRICT_CITY OF LAS PIÑAS_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'CITY OF LAS PIÑAS'),
(66, 'Benjamin Gonzales', 'Male', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/CITY OF LAS PIÑAS/Benjamin Gonzales-NCR_NCR, FOURTH DISTRICT_CITY OF LAS PIÑAS_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'CITY OF LAS PIÑAS'),
(67, 'Simnar Gran', 'Male', 'Partido Para sa Demokratikong Reporma', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/CITY OF LAS PIÑAS/Simnar Gran-NCR_NCR, FOURTH DISTRICT_CITY OF LAS PIÑAS_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'CITY OF LAS PIÑAS'),
(68, 'Michael Maestrado', 'Male', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/CITY OF LAS PIÑAS/Michael Maestrado-NCR_NCR, FOURTH DISTRICT_CITY OF LAS PIÑAS_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'CITY OF LAS PIÑAS'),
(69, 'Rey Rivera', 'Male', 'Alliance for the Common Good - Kapatiran Party', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/CITY OF LAS PIÑAS/Rey Rivera-NCR_NCR, FOURTH DISTRICT_CITY OF LAS PIÑAS_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'CITY OF LAS PIÑAS'),
(70, 'Mar-Len Abigail Binay', 'Female', 'Makatizens United Party', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/CITY OF MAKATI/Mar-Len Abigail Binay-NCR_NCR, FOURTH DISTRICT_CITY OF MAKATI_mayor.png', 'Abby', 46, '1975-12-12', 'N/A', 'No Data Available', 'Ateneo School of Law, 1997 - 2001 | UP Los Baños, Laguna', 'City Mayor, 2016 to present | City Government of Makati\r\nCongresswoman, 2007-2016 | House of Representatives | Lawyer, 2002-2007', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'CITY OF MAKATI'),
(71, 'Joel Hernandez', 'Male', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/CITY OF MAKATI/Joel Hernandez-NCR_NCR, FOURTH DISTRICT_CITY OF MAKATI_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'CITY OF MAKATI'),
(72, 'Nelson Benjamin', 'Male', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/CITY OF MUNTINLUPA/Nelson Benjamin-NCR_NCR, FOURTH DISTRICT_CITY OF MUNTINLUPA_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'CITY OF MUNTINLUPA'),
(73, 'Rozzano Rufino Biazon', 'Male', 'One Muntinlupa', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/CITY OF MUNTINLUPA/Rozzano Rufino Biazon-NCR_NCR, FOURTH DISTRICT_CITY OF MUNTINLUPA_mayor.png', 'Ruffy Biazon', 52, '1969-03-20', 'Muntinlupa City, Metro Manila', 'Degree - Medical Technology', 'University of Santo Tomas', '2019-Present – Vice Chairperson, House Committee on Appropriations | 2019-Present – Vice Chairperson, House Committee on National Defense and Security |2001-2010, 2016-Present – Congressman | 2011-2013 – Commissioner, Bureau of Customs | 1991-1992 – Director, Videogram Regulatory Board', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'CITY OF MUNTINLUPA'),
(74, 'Marc Red Mariñas ', 'Male', 'People`s Reform Party', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/CITY OF MUNTINLUPA/Marc Red Mariñas -NCR_NCR, FOURTH DISTRICT_CITY OF MUNTINLUPA_mayor.png', 'Red', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'CITY OF MUNTINLUPA'),
(75, 'Oscar Marmeto', 'Male', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/CITY OF MUNTINLUPA/Oscar Marmeto-NCR_NCR, FOURTH DISTRICT_CITY OF MUNTINLUPA_mayor.png', 'Oscar', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'CITY OF MUNTINLUPA'),
(76, 'Rolando Aguilar', 'Male', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/CITY OF PARAÑAQUE/Rolando Aguilar-NCR_NCR, FOURTH DISTRICT_CITY OF PARAÑAQUE_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'CITY OF PARAÑAQUE'),
(77, 'Gerardo Mores', 'Male', 'Pederalismo ng Dugong Dakilang Samahan', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/CITY OF PARAÑAQUE/Gerardo Mores-NCR_NCR, FOURTH DISTRICT_CITY OF PARAÑAQUE_mayor.png', 'Jherie', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'CITY OF PARAÑAQUE'),
(78, 'Eric Olivarez', 'Male', 'Partido Demokratiko Pilipino Lakas ng Bayan', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/CITY OF PARAÑAQUE/Eric Olivarez-NCR_NCR, FOURTH DISTRICT_CITY OF PARAÑAQUE_mayor.png', 'Eric', 0, '0000-00-00', 'N/A', 'History and Political Science', 'De La Salle University', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'CITY OF PARAÑAQUE'),
(79, 'John Drew Uy', 'Male', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/CITY OF PARAÑAQUE/John Drew Uy-NCR_NCR, FOURTH DISTRICT_CITY OF PARAÑAQUE_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'CITY OF PARAÑAQUE'),
(80, 'Julius Anthony Zaide', 'Male', 'Kilusang Bagong Lipunan', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/CITY OF PARAÑAQUE/Julius Anthony Zaide-NCR_NCR, FOURTH DISTRICT_CITY OF PARAÑAQUE_mayor.png', 'Jun', 39, '1982-08-28', 'N/A', 'Foreign Service (Major in Diplomacy)', 'Lyceum of the Philippines University', 'Baranggay Captain', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'CITY OF PARAÑAQUE'),
(81, 'Richard Advincula ', 'Male', 'People`s Reform Party ', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/PASAY CITY/Richard Advincula -NCR_NCR, FOURTH DISTRICT_PASAY CITY_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'Former City Counciler', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'PASAY CITY'),
(82, 'Imelda Calixto-Rubiano', 'Female', 'Partido Demokratiko Pilipino Lakas ng Bayan ', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/PASAY CITY/Imelda Calixto-Rubiano-NCR_NCR, FOURTH DISTRICT_PASAY CITY_mayor.png', 'Emi', 61, '1960-08-16', 'Pasay City, Metro Manila', 'No Data Available', 'Bachelor of Arts Major in Behavioral Science - University of Santo Tomas', '2019-Present – Mayor | 2010-2019 – Congresswoman, Pasay City | 1998-2004, 2007-2010 – Councilor', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'PASAY CITY'),
(83, 'AJ Romero ', 'Male', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/PASAY CITY/AJ Romero -NCR_NCR, FOURTH DISTRICT_PASAY CITY_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'PASAY CITY'),
(84, 'Edward Togonon ', 'Male', 'Partido sa Demokratikong Reporma', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/PASAY CITY/Edward Togonon -NCR_NCR, FOURTH DISTRICT_PASAY CITY_mayor.png', 'ET', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'PASAY CITY'),
(85, 'Marilyn Chiong', 'Female', 'Independent', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/PATEROS/Marilyn Chiong-NCR_NCR, FOURTH DISTRICT_PATEROS_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'PATEROS'),
(86, 'Miguel E Ponce III', 'Male', 'Aksyon Demokratiko', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/PATEROS/Miguel E Ponce III-NCR_NCR, FOURTH DISTRICT_PATEROS_mayor.png', 'Ike ', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'PATEROS'),
(87, 'Maria Laarni Cayetano', 'Female', 'Nacionalista Party', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/TAGUIG CITY/Maria Laarni Cayetano-NCR_NCR, FOURTH DISTRICT_TAGUIG CITY_mayor.png', 'Lani', 40, '1981-12-11', 'N/A', 'No Data Available', 'No Data Available', '2007-2010, 2019-Present –Congresswoman | 2010-2019 – Mayor', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'TAGUIG CITY'),
(88, 'Arnel Cerafica ', 'Male', 'Partido Pilipino sa Pagbabago (PPP) ', '../pictures/mayors/NATIONAL CAPITAL REGION (NCR)/NCR, FOURTH DISTRICT/TAGUIG CITY/Arnel Cerafica -NCR_NCR, FOURTH DISTRICT_TAGUIG CITY_mayor.png', 'N/A', 0, '0000-00-00', 'N/A', 'No Data Available', 'No Data Available', 'No Data Available', 'NATIONAL CAPITAL REGION (NCR)', 'NCR, FOURTH DISTRICT', 'TAGUIG CITY');

-- --------------------------------------------------------

--
-- Table structure for table `pres_candidates`
--

CREATE TABLE `pres_candidates` (
  `id` int(255) NOT NULL,
  `candidate` varchar(255) NOT NULL,
  `sex` varchar(255) NOT NULL,
  `partylist` varchar(255) NOT NULL,
  `picture_dir` text NOT NULL,
  `nickname` varchar(255) NOT NULL,
  `age` int(255) NOT NULL,
  `birthdate` date NOT NULL,
  `hometown` varchar(255) NOT NULL,
  `honorary_degree` text NOT NULL,
  `tertiary` text NOT NULL,
  `political_background` text NOT NULL,
  `stance_divorce` varchar(255) NOT NULL,
  `stance_death_penalty` varchar(255) NOT NULL,
  `stance_same_sex_marriage` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `pres_candidates`
--

INSERT INTO `pres_candidates` (`id`, `candidate`, `sex`, `partylist`, `picture_dir`, `nickname`, `age`, `birthdate`, `hometown`, `honorary_degree`, `tertiary`, `political_background`, `stance_divorce`, `stance_death_penalty`, `stance_same_sex_marriage`) VALUES
(71, 'Ernie Abella', 'Male', 'Independent', '../pictures/presidents/Ernie Abella-president.png', 'Ernie', 72, '1972-07-11', 'Davao City, Davao Region', 'No Data Available', 'Ateneo de Davao University - \r\nBA in pre-medicine | Silliman University - Master`s Degree in Divinity | Asian Institute of Management - Master`s Degree in Social Development', 'Undersecretary for Strategic \r\nCommunications and Research of the Department of Foreign Affairs (2017–2021).| Presidential Spokesperson (2016–2017)', 'Unknown', 'Yes', 'Unknown'),
(72, 'Leody De Guzman', 'Male', 'Partido Lakas ng Masa', '../pictures/presidents/Leody De Guzman-president.png', 'Ka Leody', 62, '1959-07-25', 'Naujan, Oriental Mindoro', 'No Data Available', 'Philippine Maritime Institute - Bachelor of Science in Customs Administration', 'Chairman - Bukluran ng Manggagawang Pilipino (BMP) | Councilor - International Council, International Center for Labor Solidarity | Vice President - Asia Regional Organization of Bank, Insurance and Finance Unions', 'Yes', 'No', 'Yes'),
(73, 'Isko Moreno Domagoso ', 'Male', 'Aksyon Demokratiko', '../pictures/presidents/Isko Moreno Domagoso -president.png', 'Yorme', 47, '1974-10-24', 'Manila, Philippines', 'No Data Available', 'Harvard University - Executive Leadership Program | Oxford University - Strategic Leadership Program | US State Department in Washington DC - International Visitor Leadership Program | University of the Philippines, Diliman - Executive Leadership Program | Pamantasan ng Lungsod ng Maynila - Public Administration | Arellano University - Bachelor of Laws', 'Councilor of Manila, 1st District (1998-2007) | Manila Vice Mayor (2007-2013, 2013-2016) | Chairman of the Board of the North Luzon Railways Corporation (July 2017--October 2017) | Undersecretary of Social Welfare and Development for Luzon Affairs (May2018 - October 2018) | 27th Mayor of Manila (2019-present)', 'No', 'No', 'No'),
(74, 'Norberto Gonzales', 'Male', 'Partido Demokratiko Sosyalista ng Pilipinas', '../pictures/presidents/Norberto Gonzales-president.png', 'N/A', 74, '1947-04-17', 'Balanga, Bataan', 'No Data Available', 'Ateneo de Davao University - Bachelor of Science in Pre-Medicine | National Defense College of the Philippines - Master in National Security Administration', '36th Secretary of the Department of the National Defense of the Philippines under the administration of President Gloria Macapagal Arroyo | Presidential Adviser for Special Concerns to President Gloria Macapagal-Arroyo (February 2001 to January 2004) | Arroyo`s Presidential Chief of Staff (August 2004 - February 2005) | National Security Adviser and Director-General of the National Security Council.(February of 2005 - June of 2010)', 'Unknown', 'Unknown', 'Unknown'),
(75, 'Faisal Mangondato', 'Male', 'Katipunan ng Kamalayang Kayumanggi ', '../pictures/presidents/Faisal Mangondato-president.png', 'Fai', 59, '1962-12-30', 'Ramain Ditsaan, Lanao del Sur', 'No Data Available', 'B.S. Medical Technology, Philippine Women`s University', 'No Data Available', 'Yes', 'Yes', 'Yes'),
(76, 'Ping Lacson', 'Male', 'Partido Para sa Demokratikong Reporma', '../pictures/presidents/Ping Lacson-president.png', 'Ping', 73, '1948-06-01', 'Imus, Cavite', 'No Data Available', 'Masters in Government Management\r\nPamantasan ng Lungsod ng Maynila (1995-1996)', 'Senator (2001-2013, 2016-present) Presidential Assistant for Rehabilitation and Recovery', 'Yes', 'Unknown', 'No'),
(77, 'Bongbong Marcos', 'Male', 'Partido Federal ng Pilipinas', '../pictures/presidents/Bongbong Marcos-president.png', 'Bongbong', 65, '1957-09-13', 'Ilocos Norte', 'No Data Available', 'Special Diploma in Social Studies, Oxford University', 'Senator of the Philippines (2010-2016) | Congressman, Ilocos Norte (2nd District) (2007-2010) | Governor, Ilocos Norte (1998-2007) | Congressman, Ilocos Norte (2nd District) (1992-1995) | Governor, Ilocos Norte (1983-1986) | Vice-Governor, Ilocos Norte (1980-1983)', 'Unknown', 'Yes', 'Yes'),
(78, 'Jose Montemayor Jr.', 'Male', 'Democratic Party of the Philippines', '../pictures/presidents/Jose Montemayor Jr.-president.png', 'Jojomo', 73, '1948-06-01', 'Imus, Cavite', 'No Data Available', 'Master of Divinity, Farcorner`s International Theological Seminary | Phd Public Health, Ruggero Univ. | International Master of Laws (LL.M. Cand.) - Human Rights, Ateneo de Manila University | Masters in Business Administration, University of the Philippines | Bachelor of Laws (LLB), Philippine Law School | Research fellow in cardiac catheterization, St. Luke`s Heart Institute | Fellowship in adult cardiology, St. Luke’s Heart Institute | Post graduate internship and residency in internal medicine, Cardinal Santos Medical Center | Doctor of Medicine, Far Eastern University | B.S. Medical Technology, Far Eastern University', 'No Data Available', 'No', 'Unknown', 'Unknown'),
(79, 'Manny Pacman Pacquiao', 'Male', 'Abag Promdi', '../pictures/presidents/Manny Pacman Pacquiao-president.png', 'Manny', 43, '1978-12-17', 'General Santos City', 'Doctorate of Humanities, \r\nSouthwestern University', 'Bachelor`s Degree in Political Science Majoring in Local Government Administration through the Expanded Tertiary Education Equivalency and Accreditation Program (ETEEAP), Philippine Councilors League-Legislative Academy ,2019 | BSBA Marketing Management, Notre Dame of Dadiangas University | Political Science, University of Makati\r\n', 'Representative Sarangani Province, 15th Congress, 2010 to 2013 | Representative Sarangani Province, 16th Congress, 2013 to 2016 | Senator, 17th Congress, 2016', 'Yes', 'Yes', 'No'),
(80, 'Leni Robredo', 'Female', 'Independent', '../pictures/presidents/Leni Robredo-president.png', 'Leni', 57, '1965-04-23', 'Naga, Camarines Sur', 'Doctor in Public Administration, Polytechnic University of the Philippines | Doctor of Humanities, University of Saint Anthony in Naga City | Doctor of Laws, University of the Cordilleras in Baguio City', 'B.A. in Economics, University of the Philippines-Diliman | Juris Doctor, University of Nueva Caceres | Passed the Bar Examinations in 1996 and admitted to the Philippine Bar Association', 'Vice President of the Philippines, 2016 | Representative of the 3rd District of Camarines Sur, 2013 to 2016', 'No', 'No', 'No');

-- --------------------------------------------------------

--
-- Table structure for table `vcpres_candidates`
--

CREATE TABLE `vcpres_candidates` (
  `id` int(255) NOT NULL,
  `candidate` varchar(255) NOT NULL,
  `sex` varchar(255) NOT NULL,
  `partylist` varchar(255) NOT NULL,
  `picture_dir` text NOT NULL,
  `nickname` varchar(255) NOT NULL,
  `age` int(255) NOT NULL,
  `birthdate` date NOT NULL,
  `hometown` varchar(255) NOT NULL,
  `honorary_degree` text NOT NULL,
  `tertiary` text NOT NULL,
  `political_background` text NOT NULL,
  `stance_divorce` varchar(255) NOT NULL,
  `stance_death_penalty` varchar(255) NOT NULL,
  `stance_same_sex_marriage` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `vcpres_candidates`
--

INSERT INTO `vcpres_candidates` (`id`, `candidate`, `sex`, `partylist`, `picture_dir`, `nickname`, `age`, `birthdate`, `hometown`, `honorary_degree`, `tertiary`, `political_background`, `stance_divorce`, `stance_death_penalty`, `stance_same_sex_marriage`) VALUES
(11, 'Lito Atienza', 'Male', 'Abag Promdi', '../pictures/vc_presidents/Lito Atienza-vcpresident.png', 'Lito', 80, '1941-08-10', 'San Andres Bukid, Manila', 'Doctor of Public Management, Honoris Causa, Pamantasan ng Lungsod ng Maynila', 'Master in Urban Planning, Pamantasan ng Lungsod ng Maynila | Bachelor in Public Administration, Pamantasan ng Lungsod ng Maynila\r\n', 'Deputy Speaker of the House of Representatives, Nov. 2020 to present | Representative of Buhay Party-List Group, House of Representatives, 2013 to present | Secretary, Department of Environment and Natural Resources, 2007 to 2009 | Mayor, Manila City, 1998 - 2007 | Vice Mayor, Manila City, 1992 - 1998', 'Unknown', 'Unknown', 'Unknown'),
(12, 'Walden Bello ', 'Male', 'Partido Lakas ng Masa ', '../pictures/vc_presidents/Walden Bello -vcpresident.png', 'N/A', 76, '1945-11-11', 'Cardona , Rizal', 'No Data Available', 'BA in Humanities, Ateneo de Manila University, 1966 | MA in Sociology, Princeton University, 1972 | Ph.D in Sociology, Princeton University, 1975', 'Akbayan Representative, 14th Congress, served from 2009 to 2010 | Akbayan Representative, 15th Congress, 2010 to 2013 | Akbayan Representative, 14th Congress, 2013 to 2015 (resigned)', 'Unknown', 'Unknown', 'Unknown'),
(13, 'Rizalito David', 'Male', 'Democratic Party of the Philippines', '../pictures/vc_presidents/Rizalito David-vcpresident.png', 'N/A', 60, '1962-01-12', 'Tondo, Manila', 'No Data Available', 'Sociology and Environmental Science (minor in Rural Development), University of the Philippines - Los Baños', 'Council Member, Koalisyong Katoliko Kristyano | Executive Director, Pro-Life Philippoines, Inc.| Radio commentator, Radio Veritas, Gising Kapatid and Turo ni Ina | Head Executive Assistant and Political Affairs Director, Sen. Robert Jaworski, Philippine Senate, 1998 - 2004 | Consultant on Political Affairs and Head of Political Operations in Mindanao, Deputy Speaker Hernando Perez, Houses of Representatives, 1997 - 1998 | Executive Assistant (1993 - 1995) and Political Affairs Director (1995 - 1996), Sen. Francisco Tatad, Philippine Senate | Chief, Research Monitoring Staff, Liberal Party-PDP Laban 1992 Presidential Elections, 1992 | Former Chief, Strategic Planning Section, Department of Environment and Natural Resources, 1990 - 1992\r\n', 'Unknown', 'Unknown', 'Unknown'),
(14, 'Sara Duterte', 'Female', 'Lakas Christian Muslim Democrats', '../pictures/vc_presidents/Sara Duterte-vcpresident.png', 'Inday Sara', 43, '1978-05-31', 'Davao City', 'No Data Available', 'Admitted to the Philippine Bar, 2005 | Bachelor of Laws, San Sebastian College – Recoletos, 2005 | Bachelor of Science, Respiratory Therapy, San Pedro College, 1999', 'Mayor, Davao City, 2010 - 2013; 2016 - present | Partner, Carpio & Duterte Lawyers, 2013 - 2016 | Chairman, Board-Regional Development Committee-Mindanao Area Committee of the National Economic and Development Authority | Chairperson, Regional Development Council | Vice Mayor, Davao City, 2007 – 2010 | Court Attorney, Office of the Associate Justice Romeo J. Carpio Sr., Supreme Court', 'Unknown', 'Unknown', 'Unknown'),
(15, 'Manny Lopez SD', 'Male', 'Workers and Peasants Party', '../pictures/vc_presidents/Manny Lopez SD-vcpresident.png', 'N/A', 63, '2022-03-10', 'Moncada, Tarlac', 'No Data Available', 'Business Economics Program, University of Asia and the Pacific Juris Doctor, Pacific Coast University | Business Law, Los Angeles City College | MBA, University of California, Los Angeles | Political Science and Economics, University of the Philippines - Diliman, 1981', 'Vice Chairman, National Advisory Board, Labor Party of the Philippines (a.k.a. The Workers and Peasants Party | President and General Manager at NFA Grainscor\r\n', 'Unknown', 'Unknown', 'Unknown'),
(16, 'Doc Willie Ong', 'Male', 'Aksyon Demokratiko', '../pictures/vc_presidents/Doc Willie Ong-vcpresident.png', 'N/A', 58, '1963-10-24', 'Tondo, Manila City', 'No Data Available', 'B.S. Botany, University of the Philippines-Diliman | Medical degree, De La Salle Health Science Institute | Masters in Public Health, UP - Manila', 'No Data Available', 'Unknown', 'Unknown', 'Unknown'),
(17, 'Francis Nepomuceno Pangilinan', 'Male', 'Liberal Party', '../pictures/vc_presidents/Francis Nepomuceno Pangilinan-vcpresident.png', 'Kiko', 58, '1963-08-24', 'Manila City, Metro Manila', 'No Data Available', 'Bachelor of Arts in English, Major in Comparative Literature, University of the Philippines Diliman | Bachelor of Laws, University of the Philippines Diliman | Masters in Public Administration, John F. Kennedy School of Government Harvard University Cambridge, 1997', 'Member, Senate Electoral Tribunal 18th Congress, July 2020 – present | Campaign Manager, Otso Diretso Senate slate (Liberal Party coalition), Feb. - May 2019 | Minority Leader, Commission on Appointments 17th to 18th Congress, May 2017 – June 2020 | Senator 17th to 18th Congress, June 2016 – present | Cabinet Secretary, Presidential Assistant for Food Security and Agricultural | Modernization - Office of the President, May 2014 – Sept. 2015 | Campaign Manager, Liberal Party Senate slate, Feb. - May 2010 | Senate Majority Leader, 2004 – 2008 | Senator, 12th to 14th Congress, 2001 – 2013', 'Unknown', 'Unknown', 'Unknown'),
(18, 'Carlos Gelacio Serapio ', 'Male', 'Katipunan ng Kamalayang Kayumanggi ', '../pictures/vc_presidents/Carlos Gelacio Serapio -vcpresident.png', 'N/A', 71, '1950-10-04', 'N/A', 'No Data Available', 'Serapio & de Castro Law Offices | Office of the Executive Secretary of President Benigno Aquino - Lead of Consultant Pool | Office of the Presidential Adviser on Political Affairs - Consultant | National Coastwatch Center - Office of the President - Consultant | United Nations Development Programme Local Democracy Project in Asia - Consultant | USAID Inventory and Database Project for the Court of Tax Appeals - Project Manager | Author, Christianism: A Philosophical Guide to Political Praxis | Chair and operator, LABAN Poll Watching Operations Center (1978)', 'LLB,University of the Philippines, 1975 | AB Political Science, Ateneo de Manila University, 1970', 'Unknown', 'Unknown', 'Unknown'),
(19, 'Vicente Castelo Sotto III', 'Male', 'Nationalist People`s Coalition ', '../pictures/vc_presidents/Vicente Castelo Sotto III-vcpresident.png', 'Tito Sotto', 73, '1948-08-24', 'N/A', 'No Data Available', 'Executive Program for Leaders in Development at the Harvard \r\nUniversity John F. Kennedy School of Government that he \r\ncompleted in June 2000 | AB English, Colegio de San Juan de Letran', 'Senate President (2018-present) | Senate Majority Floor Leader (2016-2018) | Senator (2013-2016) | Senate Majority Floor Leader (2010-2013) | Dangerous Drugs Board chairman (2008-2009) | Senator (1998-2004) | Senator (1992-1998)\r\n', 'Unknown', 'Unknown', 'Unknown');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `governor_candidates`
--
ALTER TABLE `governor_candidates`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `mayor_candidates`
--
ALTER TABLE `mayor_candidates`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `pres_candidates`
--
ALTER TABLE `pres_candidates`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `vcpres_candidates`
--
ALTER TABLE `vcpres_candidates`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `governor_candidates`
--
ALTER TABLE `governor_candidates`
  MODIFY `id` int(255) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=152;

--
-- AUTO_INCREMENT for table `mayor_candidates`
--
ALTER TABLE `mayor_candidates`
  MODIFY `id` int(255) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=89;

--
-- AUTO_INCREMENT for table `pres_candidates`
--
ALTER TABLE `pres_candidates`
  MODIFY `id` int(255) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=81;

--
-- AUTO_INCREMENT for table `vcpres_candidates`
--
ALTER TABLE `vcpres_candidates`
  MODIFY `id` int(255) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=20;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
